### ISSUE TITLE
leptonica error - too many open files when deskewing large files

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#105]
```
  ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
  File "/usr/local/lib/python3.5/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/__main__.py", line 870, in preprocess_deskew
  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/leptonica.py", line 525, in deskew
  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/leptonica.py", line 222, in write_implied_format
  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/leptonica.py", line 49, in __enter__
OSError: [Errno 24] Too many open files

```

**Comment by jbarlow83** [comment]
Fixed resource leak in LeptonicaErrorTrap, commit 7f64392a
