### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by seebi** [jbarlow83/OCRmyPDF#123]
I get now constant errors like this (file independent) on macosx / docker-machine (version 0.7.0, build a650a40) using these docker client / server versions. I just pulled latest image 0d49309a06ff but this did not solve the issue

````
∴ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Wed Apr 27 15:27:26 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

∴ docker run --rm -v /Users/seebi:/home/docker jbarlow83/ocrmypdf --skip-text scan.pdf ocred.pdf
Process LoggingManager-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 505, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 140, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/appenv/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.__main__ import run_pipeline
  File "/appenv/lib/python3.5/site-packages/ocrmypdf/__main__.py", line 387, in <module>
    logging_factory, __name__, [None, options.verbose])
  File "/appenv/lib/python3.5/site-packages/ruffus/proxy_logger.py", line 342, in make_shared_logger_and_proxy
    manager.start()
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 483, in start
    self._address = reader.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
````

**Comment by jbarlow83** [comment]
This works for me on macOS El Capitan, using docker-machine 0.8.2 and docker 1.12.5 from homebrew.

It looks like the problem is related to how docker is configured on your machine, because it's unable to bind a socket (this is used only for IPC - ocrmypdf does not need a network).

This makes me think there could be something wrong with your virtual box configuration for docker and you might need to reinstall docker-machine. The docker image auto-builds and has worked for almost a year so it probably worked on the April 2016 version of docker that you have installed.

**Comment by jbolda** [comment]
Just as a note, my first attempt at using this library I tried with Docker for Windows. No amount of resetting/restarting worked, and this was on a fresh install. There must be some underlying issue with sockets + Docker for Windows as I continued to get this error. I switched to using WSL and that worked out for me.
