### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getObject'

### ISSUE THREAD

**Issue by feinerer** [jbarlow83/OCRmyPDF#156]
```
$ ocrmypdf input.pdf output.pdf
  ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/pipeline.py", line 183, in repair_pdf
    pdfinfo = pdf_get_all_pageinfo(output_file)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/pageinfo.py", line 527, in pdf_get_all_pageinfo
    return [_pdf_get_pageinfo(infile, n) for n in range(pdf.numPages)]
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/pageinfo.py", line 527, in <listcomp>
    return [_pdf_get_pageinfo(infile, n) for n in range(pdf.numPages)]
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/pageinfo.py", line 512, in _pdf_get_pageinfo
    _find_images(pdf, page)]
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/pageinfo.py", line 511, in <listcomp>
    pageinfo['images'] = [im for im in
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/pageinfo.py", line 436, in _find_images
    contentstream = pypdf.pdf.ContentStream(page.getContents(), pdf)
  File "/usr/local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 2666, in __init__
    stream = stream.getObject()
AttributeError: 'NoneType' object has no attribute 'getObject'
```

This is with OCRmyPDF 4.5.5 and the same PDF that triggered issue #154.

**Comment by jbarlow83** [comment]
I handcrafted a PDF that should have the same problem yours does, reproduced the issue, and fixed it, so hopefully that will do it this time. Fixed in 4.5.6.
