### ISSUE TITLE
ocrmypdf does not stop on "Ghostscript rendering failed"

### ISSUE THREAD

**Issue by mircea** [jbarlow83/OCRmyPDF#158]
I'm having trouble with ocrmypdf when using over some PDFs created with an HP scanner. Ghostscript returns an error but ocrmypdf tries to work with its non-existent output (there's no stop/exception thrown in ghostscript.rasterize_pdf() if errors are encountered).

Would be helpful if it would stop (and maybe even show me what parameters were used with Ghostscript so that I could debug it, I assume the PDFs are somehow broken, even though they render ok - it could be a case for opening a different issue).

~~~~~~~~~~~~~~~~~~~~
$ ocrmypdf a.pdf b.pdf
  ERROR - Ghostscript rendering failed
  ERROR - Ghostscript rendering failed
  ERROR - Ghostscript rendering failed
  ERROR - Ghostscript rendering failed
  ERROR - Ghostscript rendering failed
  ERROR - Ghostscript rendering failed
  ERROR - Unexpected ruffus exception: 
    
    
    
Original exception:

    Exception #1
      '<class 'ruffus.ruffus_exceptions.RethrownJobError'>
        
        Exceptions generating parameters for
        
        task = 'ocrmypdf.pipeline.preprocess_remove_background'
        
    Original exception:
    
        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(    
            
            
            No way to run job: Input file '/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png' does not exist)' raised in ...
           Task = def ocrmypdf.pipeline.preprocess_remove_background(...):
           
        
        Traceback (most recent call last):
          File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run
            check_input_files_exist(*params)
          File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        ruffus.ruffus_exceptions.MissingInputFileError:     
            
            
            No way to run job: Input file '/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png' does not exist
        
        ' raised in ...
    Traceback (most recent call last):
      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator
        job_history, verbose_abbreviated_path):
      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run
        check_input_files_exist(*params)
      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
        "Input file '%s' does not exist" % f)
    ruffus.ruffus_exceptions.MissingInputFileError:     
        
        
        No way to run job: Input file '/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png' does not exist
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5887, in pipeline_run
        verbose)
      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5283, in fill_queue_with_job_parameters
        for params in job_parameters:
      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5215, in parameter_generator
        raise errt
    ruffus.ruffus_exceptions.RethrownJobError: 
        
        Exceptions generating parameters for
        
        task = 'ocrmypdf.pipeline.preprocess_remove_background'
        
    Original exception:
    
        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(    
            
            
            No way to run job: Input file '/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png' does not exist)' raised in ...
           Task = def ocrmypdf.pipeline.preprocess_remove_background(...):
           
        
        Traceback (most recent call last):
          File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run
            check_input_files_exist(*params)
          File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        ruffus.ruffus_exceptions.MissingInputFileError:     
            
            
            No way to run job: Input file '/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png' does not exist
        
        
    
    
  ERROR - RethrownJobError((None, None, <class 'ruffus.ruffus_exceptions.RethrownJobError'>, RethrownJobError(('ocrmypdf.pipeline.preprocess_remove_background', '', 'ruffus.ruffus_exceptions.MissingInputFileError', "(    \n    \n    \n    No way to run job: Input file '/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png' does not exist)", 'Traceback (most recent call last):\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator\n    job_history, verbose_abbreviated_path):\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run\n    check_input_files_exist(*params)\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist\n    "Input file \'%s\' does not exist" % f)\nruffus.ruffus_exceptions.MissingInputFileError:     \n    \n    \n    No way to run job: Input file \'/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png\' does not exist\n'),), 'Traceback (most recent call last):\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator\n    job_history, verbose_abbreviated_path):\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run\n    check_input_files_exist(*params)\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist\n    "Input file \'%s\' does not exist" % f)\nruffus.ruffus_exceptions.MissingInputFileError:     \n    \n    \n    No way to run job: Input file \'/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png\' does not exist\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5887, in pipeline_run\n    verbose)\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5283, in fill_queue_with_job_parameters\n    for params in job_parameters:\n  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5215, in parameter_generator\n    raise errt\nruffus.ruffus_exceptions.RethrownJobError: \n    \n    Exceptions generating parameters for\n    \n    task = \'ocrmypdf.pipeline.preprocess_remove_background\'\n    \nOriginal exception:\n\n    Exception #1\n      \'ruffus.ruffus_exceptions.MissingInputFileError(    \n        \n        \n        No way to run job: Input file \'/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png\' does not exist)\' raised in ...\n       Task = def ocrmypdf.pipeline.preprocess_remove_background(...):\n       \n    \n    Traceback (most recent call last):\n      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator\n        job_history, verbose_abbreviated_path):\n      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run\n        check_input_files_exist(*params)\n      File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist\n        "Input file \'%s\' does not exist" % f)\n    ruffus.ruffus_exceptions.MissingInputFileError:     \n        \n        \n        No way to run job: Input file \'/var/folders/mb/m67q5m7s3ns_pw_5qq66zjxw0000gn/T/com.github.ocrmypdf.gm2m91fw/000001.page.png\' does not exist\n    \n    \n'),)
~~~~~~~~~~~~~~~~~~~~

**Comment by jbarlow83** [comment]
Fixed in 4.5.6
