### ISSUE TITLE
argparse.ArgumentError is called in __main__.py with only 1 parameter, but it needs 2

### ISSUE THREAD

**Issue by mircea** [jbarlow83/OCRmyPDF#160]
I'm missing the Romanian language package for tesseract so ocrmypdf is trying to tell me this by throwing an exception.
~~~~
$ ocrmypdf -l ron a.pdf b.pdf
Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 11, in <module>
    load_entry_point('ocrmypdf==4.5.4', 'console_scripts', 'ocrmypdf')()
  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ocrmypdf/__main__.py", line 562, in run_pipeline
    check_options(options, _log)
  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ocrmypdf/__main__.py", line 366, in check_options
    check_options_languages(options, log)
  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ocrmypdf/__main__.py", line 271, in check_options_languages
    raise argparse.ArgumentError(msg)
TypeError: __init__() missing 1 required positional argument: 'message'
~~~~

Unfortunately, the code in ```__main__.py/check_options_languages()``` tries to raise the exception with only one parameter:
~~~
raise argparse.ArgumentError(msg)
~~~

Apparently, when being used like this, it needs to use 2 parameters (see usage examples in https://svn.python.org/projects/python/trunk/Lib/argparse.py). I've solved this by replacing the line above with
~~~~
raise argparse.ArgumentError(None, msg)
~~~~

This might not be the right way of doing it, though. The issue is present in all functions which raise this exception. Another example below:
~~~~
$ ocrmypdf --force-ocr --skip-text a.pdf b.pdf
Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 11, in <module>
    load_entry_point('ocrmypdf==4.5.4', 'console_scripts', 'ocrmypdf')()
  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ocrmypdf/__main__.py", line 562, in run_pipeline
    check_options(options, _log)
  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ocrmypdf/__main__.py", line 370, in check_options
    check_options_ocr_behavior(options, log)
  File "/usr/local/Cellar/ocrmypdf/4.5.4/libexec/lib/python3.6/site-packages/ocrmypdf/__main__.py", line 327, in check_options_ocr_behavior
    "Error: --force-ocr and --skip-text are mutually incompatible.")
TypeError: __init__() missing 1 required positional argument: 'message'
~~~~

**Comment by jbarlow83** [comment]
Good catch. Fixed.
