### ISSUE TITLE
page_pdf is not defined in pipeline.py

### ISSUE THREAD

**Issue by sorrell** [jbarlow83/OCRmyPDF#167]
I installed OCRmyPDF on a new docker image and ran into the following issue:

```
  ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pipeline.py", line 524, in select_visible_page_image
    page_number(page_pdf)))
NameError: name 'page_pdf' is not defined
```
Looks like that should be `image` instead of `page_pdf`, as changing that fixed my issue.

https://github.com/jbarlow83/OCRmyPDF/blob/d077c03686981c1601305cac2eb7b97e7f823a34/ocrmypdf/pipeline.py#L524

**Comment by jbarlow83** [comment]
Now fixed in HEAD.
