### ISSUE TITLE
brew install failure (reported against 4.5.6)

### ISSUE THREAD

**Issue by njm2112** [jbarlow83/OCRmyPDF#170]
Hoping to get some guidance on the follow installation issue. Full log attached.

```
==> /usr/local/Cellar/ocrmypdf/4.5.6/libexec/bin/pip install -v --no-deps --no-binary :all: -
Last 15 lines from /Users/njm/Library/Logs/Homebrew/ocrmypdf/09.pip:
  Removing source in /private/tmp/pip-zo09xslc-build
Command "/usr/local/Cellar/ocrmypdf/4.5.6/libexec/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-zo09xslc-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-46lxzkye-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/4.5.6/libexec/bin/../include/site/python3.5/reportlab" failed with error code 1 in /private/tmp/pip-zo09xslc-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/4.5.6/libexec/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/ocrmypdf/4.5.6/libexec/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/ocrmypdf/4.5.6/libexec/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/ocrmypdf/4.5.6/libexec/lib/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/ocrmypdf/4.5.6/libexec/lib/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/local/Cellar/ocrmypdf/4.5.6/libexec/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-zo09xslc-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-46lxzkye-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/4.5.6/libexec/bin/../include/site/python3.5/reportlab" failed with error code 1 in /private/tmp/pip-zo09xslc-build/
```
[2017-05-13_ocrmypdf install error.txt](https://github.com/jbarlow83/OCRmyPDF/files/998769/2017-05-13_ocrmypdf.install.error.txt)

**Comment by jbarlow83** [comment]
Unfortunately the log you provided doesn't have enough information to diagnose the problem. It only says that pip failed to build reportlab, but not why. It's probably missing a dependency. 

Try `brew doctor` to make sure Homebrew is sane and then `brew install -v ocrmypdf` to get a more detailed log file. 

Another option is to try installing reportlab from source to a test virtual environment and see what issues occur prevent it from compiling.

```
python3 -m venv test
source test/bin/activate
pip3 install --no-binary=reportlab reportlab
```

That will likely fail, but hopefully the failure message will indicate what system dependencies are missing.

**Comment by jbarlow83** [comment]
I'm addressing this at homebrew-ocrmypdf.
