### ISSUE TITLE
unicode encoding/decoding errors across test suite

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#172]
Hello,

I am trying to update OCRmyPDF to version 5.2 in Debian.

Firstly, the '©' in `compile_leptonica.py` causes `python3.6 setup.py clean` to choke:

    Skipping external program tests because of --force
    Traceback (most recent call last):
      File "setup.py", line 238, in <module>
        zip_safe=False)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 323, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 392, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 188, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 22, in execfile
        src = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2: ordinal not in range(128)

I tried simply replacing the '© with '(C)', and the package build got to the point of running the test suite, but many tests failed with similar unicode errors.  So I think that my tiny patch did not touch the real root of the problem.

Please let me know if you have any suggestions.

[ocrmypdf_5.2-1_i386-2017-07-06T12:54:27Z.build.txt](https://github.com/jbarlow83/OCRmyPDF/files/1127938/ocrmypdf_5.2-1_i386-2017-07-06T12.54.27Z.build.txt)

**Comment by jbarlow83** [comment]
This issue describes how this can occur if the system has LANG=C set

http://bugs.python.org/issue19846

Does that help?

**Comment by spwhitton** [comment]
Thank you for the hint.  I'd actually fixed an error like this in another Debian package but had forgotten; your link prompted me to find that old diff and apply an equivalent patch to OCRmyPDF.

I can't properly test the fix because the computer I'm on is not powerful enough to reach the end of the test suite before the Debian build tools time out the build, but since it doesn't fail immediately with any decoding errors, I'm closing this issue.

**Comment by jbarlow83** [comment]
Since this came up again in another packaging attempt, the fix is `export LC_ALL=C.UTF-8` (after installing the platform's locales)

See here
https://git.spwhitton.name/ocrmypdf/commit/?h=debian&id=1cfeeea8da4882115cf00b531bda2e4dbb831029
