### ISSUE TITLE
   ImportError: dynamic module does not define module export function (PyInit__sqlite3)

### ISSUE THREAD

**Issue by laoyang360** [jbarlow83/OCRmyPDF#173]
[root@455691d6 OCRmyPDF]# pip3 install . 
Processing /ssd/yc/OCRmyPDF
Collecting ruffus==2.6.3 (from ocrmypdf==5.2.post0+g3a7c341.d20170708)
  Using cached ruffus-2.6.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wchw1ow3/ruffus/setup.py", line 12, in <module>
        import ruffus.ruffus_version
      File "/tmp/pip-build-wchw1ow3/ruffus/ruffus/__init__.py", line 28, in <module>
        from .task import Pipeline, Task
      File "/tmp/pip-build-wchw1ow3/ruffus/ruffus/task.py", line 115, in <module>
        from . import dbdict
      File "/tmp/pip-build-wchw1ow3/ruffus/ruffus/dbdict.py", line 91, in <module>
        import sqlite3
      File "/usr/local/python3/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
        from sqlite3.dbapi2 import *
      File "/usr/local/python3/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
        from _sqlite3 import *
    ImportError: dynamic module does not define module export function (PyInit__sqlite3)
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wchw1ow3/ruffus/

I google for long time, now it still is a big problem for me !

**Comment by jbarlow83** [comment]
This is an OS configuration problem not something to do with ocrmypdf.

It looks like SQLite is not installed or Python was compiled without
SQLite. This error can also occur when Python 3 is trying to access a
Python 2 module. Chances are "import sqlite3" from the Python console also
fails. Check with your OS vendor.
