### ISSUE TITLE
argument of type 'NullObject' is not iterable

### ISSUE THREAD

**Issue by ghost** [jbarlow83/OCRmyPDF#179]
Seeing this error now, using tesseract 4.00.00alpha.

```
ocrmypdf -l heb+eng+fra 10282-02.pdf out.pdf -v
  DEBUG - ocrmypdf 5.3.post1+gda79e6b
  DEBUG - tesseract 4.00.00alpha
   INFO - Tesseract v4.x.alpha found. OCRmyPDF support is experimental.
  DEBUG - os.symlink(10282-02.pdf, /tmp/com.github.ocrmypdf.w3qtk4_d/origin)

________________________________________
Tasks which will be run:


Task enters queue = 'ocrmypdf.pipeline.triage' 
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.w3qtk4_d/origin, /tmp/com.github.ocrmypdf.w3qtk4_d/origin.pdf)
Completed Task = 'ocrmypdf.pipeline.triage' 
Task enters queue = 'ocrmypdf.pipeline.repair_pdf' 
  DEBUG - 
    
    
    
Original exception:

    Exception #1
      'builtins.TypeError(argument of type 'NullObject' is not iterable)' raised in ...
       Task = def ocrmypdf.pipeline.repair_pdf(...):
       Job  = [.../origin.pdf -> .../origin.repaired.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>]
    
    Traceback (most recent call last):
      File "/home/uri/.local/lib/python3.5/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/home/uri/.local/lib/python3.5/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/home/uri/.local/lib/python3.5/site-packages/ocrmypdf/pipeline.py", line 189, in repair_pdf
        pdfinfo = PdfInfo(output_file)
      File "/home/uri/.local/lib/python3.5/site-packages/ocrmypdf/pdfinfo.py", line 685, in __init__
        self._pages = _pdf_get_all_pageinfo(infile)
      File "/home/uri/.local/lib/python3.5/site-packages/ocrmypdf/pdfinfo.py", line 599, in _pdf_get_all_pageinfo
        return [PageInfo(pdf, n) for n in range(pdf.numPages)]
      File "/home/uri/.local/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1158, in <lambda>
        numPages = property(lambda self: self.getNumPages(), None, None)
      File "/home/uri/.local/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1155, in getNumPages
        self._flatten()
      File "/home/uri/.local/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1520, in _flatten
        self._flatten(page.getObject(), inherit, **addt)
      File "/home/uri/.local/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1509, in _flatten
        if "/Type" in pages:
    TypeError: argument of type 'NullObject' is not iterable
```

**Comment by jbarlow83** [comment]
That's something to do with the PDF's internal structure (not the Tesseract version). Can you send me the input file?

If it is not possible to share the file with me, you could try rewriting the PDF using the instructions here:
https://ocrmypdf.readthedocs.io/en/latest/errors.html#input-file-filename-is-not-a-valid-pdf

**Comment by jbarlow83** [comment]
Fixed by removal of PyPDF2
