### ISSUE TITLE
Can't write plaintext sidecar for non-ASCII scripts with Docker

### ISSUE THREAD

**Issue by ryanfb** [jbarlow83/OCRmyPDF#184]
If I run e.g.:

    docker run -v /home/ryan:/home/docker jbarlow83/ocrmypdf-polyglot -l rus --force-ocr --sidecar=russian-ocr.txt russian.pdf russian-ocr.pdf

I get:
```
  ERROR - Traceback (most recent call last):
  File "/appenv/lib/python3.5/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/appenv/lib/python3.5/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/appenv/lib/python3.5/site-packages/ocrmypdf/pipeline.py", line 965, in merge_sidecars
    write_pages(out)
  File "/appenv/lib/python3.5/site-packages/ocrmypdf/pipeline.py", line 955, in write_pages
    stream.write(in_.read())
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

If I use it without `--sidecar` I get the normal PDF output. I think this is because the default locale for Ubuntu in Docker is unset, and winds up defaulting to ASCII.

**Comment by ryanfb** [comment]
Works for me with 952f0cca1551c7afe8040ced82175e0fb2f3558f
