### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by wanghaisheng** [jbarlow83/OCRmyPDF#189]
```
➜  lab git:(master) ✗ docker run --rm -v "$(pwd):/home/docker"   ocrmypdf --output-type pdf --pdf-renderer tesseract --image-dpi 300 --force-ocr -l  chi_sim+eng --sidecar output.txt  c83d7218jw1exnrpn91vwj22i81sfb29.jpg output.pdf
WARNING - The 'tesseract' PDF renderer is deprecated.
   INFO - Tesseract v4.x.alpha found. OCRmyPDF support is experimental.
   INFO - Input file is not a PDF, checking if it is an image...
   INFO - Input file is an image
   INFO - Input image has no ICC profile, assuming sRGB
   INFO - Image seems valid. Try converting to PDF...
   INFO - Successfully converted to PDF, processing...
  ERROR - Traceback (most recent call last):
  File "/appenv/lib/python3.5/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/appenv/lib/python3.5/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/appenv/lib/python3.5/site-packages/ocrmypdf/pipeline.py", line 959, in merge_sidecars
    write_pages(out)
  File "/appenv/lib/python3.5/site-packages/ocrmypdf/pipeline.py", line 949, in write_pages
    stream.write(in_.read())
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)

```
![Uploading c83d7218jw1exnrpn91vwj22i81sfb29.jpg…]()

**Comment by jbarlow83** [comment]
I think this is the same as #184 - pull the docker image(s) again, and that should take care of it.

**Comment by jbarlow83** [comment]
By the way, you should be able to remove the argument `--pdf-renderer tesseract` when using Tesseract 4.

I'll close this for now. Please re-open if you have issues with the latest Docker images.
