### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by soto2080** [jbarlow83/OCRmyPDF#190]
Here is the log.
> ks-MacBook-Pro:downloads k$ ocrmypdf input.pdf output.pdf
  ERROR - Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ocrmypdf/pipeline.py", line 189, in repair_pdf
    pdfinfo = PdfInfo(output_file)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 685, in __init__
    self._pages = _pdf_get_all_pageinfo(infile)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 599, in _pdf_get_all_pageinfo
    return [PageInfo(pdf, n) for n in range(pdf.numPages)]
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 599, in <listcomp>
    return [PageInfo(pdf, n) for n in range(pdf.numPages)]
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 605, in __init__
    self._pageinfo = _pdf_get_pageinfo(pdf, pageno)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 565, in _pdf_get_pageinfo
    pageinfo['has_text'] = _page_has_text(pdf, page)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 533, in _page_has_text
    text = page.extractText()
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/PyPDF2/pdf.py", line 2595, in extractText
    content = ContentStream(content, self.pdf)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/PyPDF2/pdf.py", line 2673, in __init__
    stream = BytesIO(b_(stream.getData()))
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/PyPDF2/generic.py", line 841, in getData
    decoded._data = filters.decodeStreamData(self)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/PyPDF2/filters.py", line 346, in decodeStreamData
    data = FlateDecode.decode(data, stream.get("/DecodeParms"))
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/PyPDF2/filters.py", line 111, in decode
    data = decompress(data)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/PyPDF2/filters.py", line 49, in decompress
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect data check

**Comment by jbarlow83** [comment]
Looks like one of the pages is corrupt although the rest of the file is
valid.

Please attach a copy if you can.

You might be able to work around by using pdftk to explore the file into
single page files, ocr the pieces, and then reassemble.

**Comment by soto2080** [comment]
The file I tried to OCR is this

> https://drive.google.com/open?id=0B5pZx0fwHoYFbVJ4ZTJ2ZVhqZmc
So there are no tools to determine what pages are corrupt?

**Comment by jbarlow83** [comment]
It appears that a compressed object inside the PDF is corrupt but, the PDF container is structurally valid. Not every error checker is going to find that.

I have some advice on fixing corrupt PDFs here:
https://ocrmypdf.readthedocs.io/en/latest/errors.html#input-file-filename-is-not-a-valid-pdf

I was curious about the particular way this one failed and tried Ghostscript. It ran to completion, so if you first run Ghostscript on the file using the command above, and then ocrmypdf would work.

If someone submits another file that triggers the same stack trace I will wrap up with a cleaner error message.
