### ISSUE TITLE
error on MacOs

### ISSUE THREAD

**Issue by M-DFK** [jbarlow83/OCRmyPDF#240]
ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)

**Comment by jbarlow83** [comment]
**Please include the command line and (if needed) a test file with your issue report.**
