### ISSUE TITLE
Cant get OCRmyPDF to work on ubuntu 16.04

### ISSUE THREAD

**Issue by andrewbaker00** [jbarlow83/OCRmyPDF#251]
Runing on ubuntu 16.04 (heroku stack with [limited packages preinstalled](https://devcenter.heroku.com/articles/stack-packages)). 

ocrmypdf 5.4
tesseract 3.04.01
 leptonica-1.73
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.0

The following tesseract only command works fine:
```
tesseract test.jpg out
```
But when running the following ocrmypdf command:

```
ocrmypdf test.pdf out.pdf
```

i get the error below, any ideas?

```
~ $ ocrmypdf test.pdf out.pdf
  ERROR -    3: [tesseract] read_params_file: Can't open hocr
  ERROR -    3: [tesseract] read_params_file: Can't open txt
  ERROR -    2: [tesseract] read_params_file: Can't open hocr
  ERROR -    2: [tesseract] read_params_file: Can't open txt
  ERROR -    1: [tesseract] read_params_file: Can't open hocr
  ERROR -    1: [tesseract] read_params_file: Can't open txt
  ERROR - Unexpected ruffus exception: 
    
    
    
Original exception:

    Exception #1
      '<class 'ruffus.ruffus_exceptions.RethrownJobError'>
        
        Exceptions generating parameters for
        
        task = 'ocrmypdf.pipeline.render_hocr_page'
        
    Original exception:
    
        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(    
            
            
            No way to run job: Input file '/tmp/com.github.ocrmypdf.jwb7gjf2/000001.hocr' does not exist)' raised in ...
           Task = def ocrmypdf.pipeline.render_hocr_page(...):
           
        
        Traceback (most recent call last):
          File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run
            check_input_files_exist(*params)
          File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        ruffus.ruffus_exceptions.MissingInputFileError:     
            
            
            No way to run job: Input file '/tmp/com.github.ocrmypdf.jwb7gjf2/000001.hocr' does not exist
        
        ' raised in ...
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator
        job_history, verbose_abbreviated_path):
      File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run
        check_input_files_exist(*params)
      File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
        "Input file '%s' does not exist" % f)
    ruffus.ruffus_exceptions.MissingInputFileError:     
        
        
        No way to run job: Input file '/tmp/com.github.ocrmypdf.jwb7gjf2/000001.hocr' does not exist
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 5887, in pipeline_run
        verbose)
      File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 5283, in fill_queue_with_job_parameters
        for params in job_parameters:
      File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 5215, in parameter_generator
        raise errt
    ruffus.ruffus_exceptions.RethrownJobError: 
        
        Exceptions generating parameters for
        
        task = 'ocrmypdf.pipeline.render_hocr_page'
        
    Original exception:
    
        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(    
            
            
            No way to run job: Input file '/tmp/com.github.ocrmypdf.jwb7gjf2/000001.hocr' does not exist)' raised in ...
           Task = def ocrmypdf.pipeline.render_hocr_page(...):
           
        
        Traceback (most recent call last):
          File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 5118, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/task.py", line 4945, in job_needs_to_run
            check_input_files_exist(*params)
          File "/app/.heroku/python/lib/python3.6/site-packages/ruffus/file_name_parameters.py", line 399, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        ruffus.ruffus_exceptions.MissingInputFileError:     
            
            
            No way to run job: Input file '/tmp/com.github.ocrmypdf.jwb7gjf2/000001.hocr' does not exist

```

**Comment by jbarlow83** [comment]
1. See if you can run 

```
tesseract test.jpg test hocr
```

and get file named `test.hocr`. Possibly tesseract is installed but missing config files.

2. Try a newer Ubuntu (16.10+) or install with ``pip3 install ocrmypdf`` as suggested in the installation documentation.

**Comment by andrewbaker00** [comment]
Nope. Got:
```
~ $ tesseract test.jpg test hocr
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
read_params_file: Can't open hocr

**Comment by jbarlow83** [comment]
Tesseract is definitely not installed correctly then.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by nijanthan0** [comment]
i too have same problem

**Comment by muhammadahmedzahid** [comment]
same problem

**Comment by jbarlow83** [comment]
No longer supported - please try a new version of ubuntu and ocrmypdf
