### ISSUE TITLE
--Remove-background with tiff images generates error

### ISSUE THREAD

**Issue by jmrichardson** [jbarlow83/OCRmyPDF#260]
Error:

> $ ocrmypdf --remove-background --clean almonds.tiff new.pdf
>    INFO - Input file is not a PDF, checking if it is an image...
>    INFO - Input file is an image
>    INFO - Image seems valid. Try converting to PDF...
>    INFO - Successfully converted to PDF, processing...
>   ERROR - Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
>     register_cleanup, touch_files_only)
>   File "/usr/local/lib/python3.6/dist-packages/ruffus/task.py", line 567, in job_wrapper_io_files
>     ret_val = user_defined_work_func(*params)
>   File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pipeline.py", line 537, in preprocess_remove_background
>     leptonica.remove_background(input_file, output_file)
>   File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/leptonica.py", line 560, in remove_background
>     pix = pix.background_norm(tile_size=tile_size).gamma_trc(
>   File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/leptonica.py", line 440, in background_norm
>     smooth_kernel[1]
>   File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/leptonica.py", line 98, in __exit__
>     raise LeptonicaError(leptonica_output)
> ocrmypdf.leptonica.LeptonicaError: Error in pixGetInvBackgroundMap: w and h must be >= 5
> Error in pixBackgroundNorm: pixmi not made
> Error in pixBackgroundNorm: pixd not made
> Error in pixCopyResolution: pixd not defined

Version:

> $ ocrmypdf --version
> 6.1.5.post0+g0b10db9.d20180418

**Comment by jmrichardson** [comment]
Yes, the image was too small.  Thank you!
