### ISSUE TITLE
UnicodeEncodeError when invoking ocrmypdf

### ISSUE THREAD

**Issue by rodrigoesborges** [jbarlow83/OCRmyPDF#275]
Installed with pip from github repo

  ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/home/GuigUse/Música/cantoafoxe/src/ocrmypdf/src/ocrmypdf/pipeline.py", line 915, in generate_postscript_stub
    generate_pdfa_ps(output_file, pdfmark)
  File "/home/GuigUse/Música/cantoafoxe/src/ocrmypdf/src/ocrmypdf/pdfa.py", line 220, in generate_pdfa_ps
    f.write(ps)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfa' in position 274: ordinal not in range(128)

**Comment by jbarlow83** [comment]
The immediate cause looks to be the accent on Música in the installation
folder. If you create a virtual environment in a folder with pure ASCII
name that should avoid this issue, if you want a solution before the next
release.

**Comment by rodrigoesborges** [comment]
Thank you it worked!
