### ISSUE TITLE
Installation docs do not mention manual install of Exempi

### ISSUE THREAD

**Issue by rbubley** [jbarlow83/OCRmyPDF#276]
`ocrmypdf -l eng --output-type pdf --deskew test.pdf test.ocr.pdf`

The installation instructions don't say that a manual install of the Exempi library may be necessary, as the requirement `python-xmp-toolkit` does not install it for you. Without this (depending on your environment), mine being MacOS, you can get:

```
Traceback (most recent call last):
  File "/opt/local/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.__main__ import run_pipeline
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ocrmypdf/__init__.py", line 37, in <module>
    from . import pdfa
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ocrmypdf/pdfa.py", line 28, in <module>
    from libxmp.utils import file_to_dict
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/libxmp/__init__.py", line 50, in <module>
    from .core import XMPMeta, XMPIterator
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/libxmp/core.py", line 50, in <module>
    from . import exempi as _cexempi
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/libxmp/exempi.py", line 69, in <module>
    EXEMPI = _load_exempi()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/libxmp/exempi.py", line 60, in _load_exempi
    raise ExempiLoadError('Exempi library not found.')
libxmp.ExempiLoadError: Exempi library not found.
```

**Comment by jbarlow83** [comment]
Thanks for reporting.

The Homebrew formula, when updated, should take care of this automatically.
