### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by kshishir** [jbarlow83/OCRmyPDF#278]
I am getting  memory error when running ocrmypdf on a three page pdf which contains scanned images.
First two pages are full page scanned image text. 
cmd: ocrmypdf <input.pdf> <output.pdf>
It is running on red linux centos7 with 8 core and 64GB RAM.
The file is only 758KB. Has anyone faced this issue before and any suggestions to resolve it?

` ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 748, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 566, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/_pipeline.py", line 160, in repair_and_parse_pdf
    pdfinfo = PdfInfo(output_file)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 722, in __init__
    self._pages = _pdf_get_all_pageinfo(infile)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 636, in _pdf_get_all_pageinfo
    return [PageInfo(pdf, n, infile) for n in range(len(pdf.pages))]
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 636, in <listcomp>
    return [PageInfo(pdf, n, infile) for n in range(len(pdf.pages))]
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 643, in __init__
    self._pageinfo = _pdf_get_pageinfo(pdf, pageno, infile)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 597, in _pdf_get_pageinfo
    pageinfo['textinfo'] = _page_get_textblocks(fspath(infile), pageno)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfinfo.py", line 515, in _page_get_textblocks
    gstext = ghostscript.extract_text(infile, pageno+1)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/exec/ghostscript.py", line 81, in extract_text
    p = run(args_gs, stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 1546, in _communicate
    stderr = b''.join(stderr)
MemoryError
`

**Comment by jbarlow83** [comment]
The error was caused by Ghostscript. My guess is that your file caused
Ghostscript to enter an infinite loop that filled the output buffer.

I cannot help you further unless you can provide the file. You could send
it in a private Gist.

**Comment by kshishir** [comment]
It was probably some issue with the PDF form. I was able to run it by printing, scanning and running ocr again.

**Comment by jbarlow83** [comment]
If you have the opportunity, check if the command 

```
gs -sDEVICE=txtwrite -dTextFormat=0 -o output.txt yourpdf.pdf
```

creates an infinite loop on the original PDF, and if so, report the issue at bugs.ghostscript.com.

**Comment by kshishir** [comment]
Yes. Looks like gs was the issue. I was getting “File has unbalanced q/Q operators (too many Q’s)”. I updated gs to 9.23 and it works fine now.
