### ISSUE TITLE
Error when using batch commands

### ISSUE THREAD

**Issue by gabriellluz** [jbarlow83/OCRmyPDF#312]
I'm trying to OCR all my PDF files inside the current folder and all the subfolders. The command below seems to find all files but I get an error.

`find . -name '*.pdf' -print | parallel --tag -j 2 ocrmypdf -v --pdfa-image-compression auto '{}' 'output/{}' ::: *.pdf`

Error:
```
Linux Manual.pdf Original exception:
Linux Manual.pdf
Linux Manual.pdf     Exception #1
Linux Manual.pdf       'ocrmypdf.exceptions.PriorOcrFoundError' raised in ...
Linux Manual.pdf        Task = def ocrmypdf.pipeline.ocr_or_skip(...):
Linux Manual.pdf        Job  = [[.../000001.page.pdf, .../000002.page.pdf, .../000003.page.pdf, .../000004.page.pdf, .../000005.page.pdf, .../000006.page.pdf, .../000007.page.pdf, .../000008.page.pdf, .../000009.page.pdf, .../000010.page.pdf, .../000011.page.pdf, .../000012.page.pdf, .../000013.page.pdf, .../000014.page.pdf, .../000015.page.pdf, .../000016.page.pdf, .../000017.page.pdf, .../000018.page.pdf, .../000019.page.pdf, .../000020.page.pdf, .../000021.page.pdf, .../000022.page.pdf, .../000023.page.pdf, .../000024.page.pdf, .../000025.page.pdf, .../000026.page.pdf, .../000027.page.pdf, .../000028.page.pdf, .../000029.page.pdf, .../000030.page.pdf, .../000031.page.pdf, .../000032.page.pdf, .../000033.page.pdf, .../000034.page.pdf, .../000035.page.pdf, .../000036.page.pdf, .../000037.page.pdf, .../000038.page.pdf, .../000039.page.pdf, .../000040.page.pdf, .../000041.page.pdf, .../000042.page.pdf, .../000043.page.pdf, .../000044.page.pdf, .../000045.page.pdf, .../000046.page.pdf, .../000047.page.pdf, .../000048.page.pdf, .../000049.page.pdf, .../000050.page.pdf, .../000051.page.pdf] -> [.../*.ocr.page.pdf, .../*.skip.page.pdf], <LoggingProxy>, <ocrmypdf.pipeline.JobContext>]
Linux Manual.pdf     
Linux Manual.pdf     Traceback (most recent call last):
Linux Manual.pdf       File "/usr/lib/python3/dist-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
Linux Manual.pdf         register_cleanup, touch_files_only)
Linux Manual.pdf       File "/usr/lib/python3/dist-packages/ruffus/task.py", line 567, in job_wrapper_io_files
Linux Manual.pdf         ret_val = user_defined_work_func(*params)
Linux Manual.pdf       File "/usr/lib/python3/dist-packages/ocrmypdf/pipeline.py", line 389, in ocr_or_skip
Linux Manual.pdf         '.ocr.page.pdf' if is_ocr_required(pageinfo, log, options) \
Linux Manual.pdf       File "/usr/lib/python3/dist-packages/ocrmypdf/pipeline.py", line 281, in is_ocr_required
Linux Manual.pdf         raise PriorOcrFoundError()
Linux Manual.pdf     ocrmypdf.exceptions.PriorOcrFoundError
Linux Manual.pdf     
Linux Manual.pdf     
Linux Manual.pdf
Linux Manual.pdf ________________________________________
Linux Manual.pdf Tasks which will be run:
Linux Manual.pdf
Linux Manual.pdf
Linux Manual.pdf Task enters queue = 'ocrmypdf.pipeline.triage' 
Linux Manual.pdf Completed Task = 'ocrmypdf.pipeline.triage' 
Linux Manual.pdf Task enters queue = 'ocrmypdf.pipeline.repair_and_parse_pdf' 
Linux Manual.pdf Completed Task = 'ocrmypdf.pipeline.repair_and_parse_pdf' 
Linux Manual.pdf Task enters queue = 'ocrmypdf.pipeline.generate_postscript_stub' 
Linux Manual.pdf Task enters queue = 'ocrmypdf.pipeline.pre_split_pages' 
Linux Manual.pdf Completed Task = 'ocrmypdf.pipeline.generate_postscript_stub' 
Linux Manual.pdf Completed Task = 'ocrmypdf.pipeline.pre_split_pages' 
Linux Manual.pdf Task enters queue = 'ocrmypdf.pipeline.split_page' 
Linux Manual.pdf Completed Task = 'ocrmypdf.pipeline.split_page' 
Linux Manual.pdf Task enters queue = 'ocrmypdf.pipeline.ocr_or_skip' 
```

**Comment by jbarlow83** [comment]
The file in question already contains printable text so it does not need OCR, so ocrmypdf stops processing it.

See here for more details: https://ocrmypdf.readthedocs.io/en/latest/advanced.html#when-ocr-is-skipped
