### ISSUE TITLE
Don't run under win 32bit

### ISSUE THREAD

**Issue by xpbliss** [jbarlow83/OCRmyPDF#341]
when i run the ocrmypdf under windows 32bit.   it shows the error:
```
Traceback (most recent call last):
  File "c:\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37-32\Scripts\ocrmypdf.exe\__main__.py", line 5, in <module>
  File "c:\python37-32\lib\site-packages\ocrmypdf\__init__.py", line 44, in <mod
ule>
    from . import leptonica
  File "c:\python37-32\lib\site-packages\ocrmypdf\leptonica.py", line 42, in <mo
dule>
    lept = ffi.dlopen(find_library('lept'))
OSError: cannot load library '<None>': error 0x57
```

**Comment by jbarlow83** [comment]
Yes, [Windows is not supported](https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-on-windows) unfortunately.
