### ISSUE TITLE
Error with --output-type pdf option

### ISSUE THREAD

**Issue by freestyle68** [jbarlow83/OCRmyPDF#342]
Hello,

**Describe the issue**
Cannot ocr the attached file with --output-type pdf option. Otherwise no problem.

**To Reproduce**
ocrmypdf -l ita+eng --output-type pdf file.pdf file.pdf

The output is:
```
WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
/usr/local/lib/python3.6/dist-packages/pikepdf/models/metadata.py:293: UserWarning: The metadata field /CreationDate could not be copied to XMP
  warn(msg)
  ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pikepdf/models/metadata.py", line 176, in fromisoformat
    return datetime.strptime(datestr, "%Y-%m-%dT%H:%M:%S%z")
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '0000-08-05T03:40:56' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/lib/python3.6/dist-packages/ruffus/task.py", line 544, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_pipeline.py", line 875, in metadata_fixup
    "The following metadata fields were not copied: %r", not_copied
  File "/usr/local/lib/python3.6/dist-packages/pikepdf/models/metadata.py", line 324, in __exit__
    self._apply_changes()
  File "/usr/local/lib/python3.6/dist-packages/pikepdf/models/metadata.py", line 380, in _apply_changes
    self._update_docinfo()
  File "/usr/local/lib/python3.6/dist-packages/pikepdf/models/metadata.py", line 344, in _update_docinfo
    value = converter.docinfo_from_xmp(value)
  File "/usr/local/lib/python3.6/dist-packages/pikepdf/models/metadata.py", line 193, in docinfo_from_xmp
    dateobj = fromisoformat(xmp_val)
  File "/usr/local/lib/python3.6/dist-packages/pikepdf/models/metadata.py", line 178, in fromisoformat
    return datetime.strptime(datestr, "%Y-%m-%dT%H:%M:%S")
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 528, in _strptime
    datetime_date(year, 1, 1).toordinal() + 1
ValueError: year 0 is out of range

```

**Example file**
Attached is the (confidential) encrypted file.

Please check any or all that apply about the test file:

- [x] This is the input file
- [ ] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

OS: Ubuntu 18.04
OCRmyPDF Version: 8.0.0
root@ubuntu:~# tesseract --version
tesseract 4.0.0-153-g238cb2
 leptonica-1.77.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
Python 3.7.1
ghostscript 9.26
libexempi3 2.4.5
qpdf 8.3.0
jbig2enc 0.29 compiled from source
pngquant 2.5.0-2
unpaper 6.1

Thank you

[file.pdf.gpg.zip](https://github.com/jbarlow83/OCRmyPDF/files/2766483/file.pdf.gpg.zip)

**Comment by jbarlow83** [comment]
Thanks for reporting this problem.

Upgrading to ocrmypdf 8.0.1 and pikepdf 1.0.5 will resolve this issue.

**Comment by freestyle68** [comment]
Yes, it solved. Thank you.
