### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by soumenseth** [jbarlow83/OCRmyPDF#343]
Hi,
I just run the command line for ocr. It's throwing me a ValueError.

My command line : 
```bash
ocrmypdf  --tesseract-timeout 300 input.pdf output.pdf
```

The error message that I get:
```bash
ERROR - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pipeline.py", line 222, in repair_and_parse_pdf
    pdfinfo = PdfInfo(output_file)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 725, in __init__
    self._pages = _pdf_get_all_pageinfo(infile)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 642, in _pdf_get_all_pageinfo
    return [PageInfo(pdf, n, infile) for n in range(pdf.numPages)]
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 642, in <listcomp>
    return [PageInfo(pdf, n, infile) for n in range(pdf.numPages)]
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 649, in __init__
    self._pageinfo = _pdf_get_pageinfo(pdf, pageno, infile)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 608, in _pdf_get_pageinfo
    pageinfo['has_text'] = _naive_find_text(pdf=pdf, page=page)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 560, in _naive_find_text
    contentsinfo = _interpret_contents(contentstream, UNIT_SQUARE)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 188, in _interpret_contents
    _matrix_from_shorthand(operands), ctm)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 98, in _matrix_from_shorthand
    a, b, c, d, e, f = map(float, shorthand)
ValueError: not enough values to unpack (expected 6, got 5)
```
Please tell me how to fix this.

**Comment by jbarlow83** [comment]
That seems to be an old version. Please try installing a newer version to see if it has the same problem.
https://ocrmypdf.readthedocs.io/en/latest/installation.html

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by TharunAts** [comment]
I am  facing the same issue...Please let me know if there is any solution..

**Comment by jbarlow83** [comment]
As mentioned this issue probably occurs because you are running an old version
https://github.com/jbarlow83/OCRmyPDF/issues/343#issuecomment-456234267
