### ISSUE TITLE
modulenotfounderror: no module named 'chardet'

### ISSUE THREAD

**Issue by maxandersen** [jbarlow83/OCRmyPDF#344]
**Describe the issue**
running latest dockerhub results in:

```
Traceback (most recent call last):
  File "/appenv/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.__main__ import run_pipeline
  File "/appenv/lib/python3.6/site-packages/ocrmypdf/__init__.py", line 38, in <module>
    from . import pdfinfo
  File "/appenv/lib/python3.6/site-packages/ocrmypdf/pdfinfo/__init__.py", line 31, in <module>
    from .layout import get_page_analysis, get_text_boxes
  File "/appenv/lib/python3.6/site-packages/ocrmypdf/pdfinfo/layout.py", line 23, in <module>
    import pdfminer.encodingdb
  File "/appenv/lib/python3.6/site-packages/pdfminer/encodingdb.py", line 3, in <module>
    from .psparser import PSLiteral
  File "/appenv/lib/python3.6/site-packages/pdfminer/psparser.py", line 11, in <module>
    from .utils import choplist
  File "/appenv/lib/python3.6/site-packages/pdfminer/utils.py", line 13, in <module>
    import chardet  # For str encoding detection in Py3
ModuleNotFoundError: No module named 'chardet'
```

**To Reproduce**
What command line were you trying to run?

```bash
docker run -i -v $(pwd):/home/docker jbarlow83/ocrmypdf-polyglot  --deskew --output-type pdf -l fra+deu+eng+dan
```

**System:**

- OS: macOS
- OCRmyPDF Version:  jbarlow83/ocrmypdf-polyglot:latest

**Comment by jbarlow83** [comment]
It seems that the Docker image did not rebuild when it should have. Please try pulling it again.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
