### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findall'

### ISSUE THREAD

**Issue by kopperud** [jbarlow83/OCRmyPDF#358]
Hi

I tried to OCR this PDF:

[https://drive.google.com/open?id=1yzUr-2rO3e-uh1MA0cha7czOtWHZn_Jq]

I ran this command:

```
ocrmypdf  --force-ocr Gordon1968.pdf Gordon1968_ocr.pdf
```

Then I get this error:

```
  ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 544, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_pipeline.py", line 867, in metadata_fixup
    not_copied = set(meta_original.keys()) - set(meta.keys())
  File "/usr/lib64/python3.6/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/local/lib64/python3.6/site-packages/pikepdf/models/metadata.py", line 491, in __iter__
    for node, attrib, _val, _parents in self._get_elements():
  File "/usr/local/lib64/python3.6/site-packages/pikepdf/models/metadata.py", line 457, in _get_elements
    for rdfdesc in rdf.findall('rdf:Description[@rdf:about=""]', self.NS):
AttributeError: 'NoneType' object has no attribute 'findall'
```

## My setup

* ocrmypdf version 8.0.0
* Tesseract version 4.0.0-297-gec8f
* OS: Fedora 28

Any idea why this might happen? I've used this library a lot and apart from this issue it is fantastic.

Cheers
Bjørn

[Gordon1968.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2900292/Gordon1968.pdf)

**Comment by Alibaba167** [comment]
Same here...
# My Setup:
* ocrmypdf version 8.0.1 and 8.1.0
* Tesseract Version 4.0.0
* Leptonica 1.77.0
* Python 3.7.2
* OS: Arch Linux

Installed from AUR

**Comment by jbarlow83** [comment]
See here
https://github.com/pikepdf/pikepdf/issues/23

**Comment by kopperud** [comment]
Thanks. OCRing this PDF is not crucial to me, but figured It would be nice to get a solution. 

Please don't archive the PDF in any test suite, I believe it is under copyright

Looking forward to a fix in future release.

**Comment by bergamote** [comment]
This worked for me:
`pip3 install pikepdf==1.1.0`
