### ISSUE TITLE
Divide by zero in optimize.py

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#383]
**Describe the issue**
```
ERROR - Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.6/site-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/ruffus/task.py", line 544, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/ocrmypdf/_pipeline.py", line 886, in optimize_pdf
    optimize(input_file, output_file, log, context)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/ocrmypdf/optimize.py", line 469, in optimize
    ratio = input_size / output_size
ZeroDivisionError: division by zero
```

**To Reproduce**
Maybe out of disk space?
1548.2of2

**Comment by bsnipes** [comment]
I hit this same error and it was because of disk space for me. In my case, I was OCRing a 347 page PDF and OCRmyPDF filled up my /tmp filesystem. It used over 16 GB of space for that one PDF. Is there a way of telling OCRmyPDF where to put the temp storage it needs?

**Comment by jbarlow83** [comment]
Yes, you can override the `TMPDIR` envvar to put it wherever you like.

**Comment by jbarlow83** [comment]
Next release will test for div by 0 and assume it's a disk space error
