### ISSUE TITLE
bad character range Z-V at position 29

### ISSUE THREAD

**Issue by flopes89** [jbarlow83/OCRmyPDF#394]
**Describe the issue**
Error is thrown on some documents (not entirely sure what triggers it)

**To Reproduce**
```bash
parallel --tag -j2 ocrmypdf -l deu '{}' '{}' ::: *.pdf
```

**Example file**
I can't really upload a file as it's all personal information. If need be maybe I can redact one if someone has a free tool for that?

**Expected behavior**
I don't except any errors on any files.

However, the file seems to have been processes with OCR even though an error was thrown... So it seems to not impact the OCR itself...

**System:**

- OS: Windows 10 Home using Ubuntu WSL
- OCRmyPDF Version: 6.1.2

**Error trace:**
```
20071127162959.pdf      ERROR - Unexpected ruffus exception:
20071127162959.pdf
20071127162959.pdf
20071127162959.pdf
20071127162959.pdf    Original exception:
20071127162959.pdf
20071127162959.pdf        Exception #1
20071127162959.pdf          '<class 'sre_constants.error'>bad character range Z-V at position 29' raised in ...
20071127162959.pdf        Traceback (most recent call last):
20071127162959.pdf          File "/usr/lib/python3/dist-packages/ruffus/task.py", line 5840, in pipeline_run
20071127162959.pdf            for o_f_n in get_job_result_output_file_names(job_result):
20071127162959.pdf          File "/usr/lib/python3/dist-packages/ruffus/task.py", line 5372, in get_job_result_output_file_names
20071127162959.pdf            for o_f_n in glob.glob(possible_glob_str):
20071127162959.pdf          File "/usr/lib/python3.6/glob.py", line 20, in glob
20071127162959.pdf            return list(iglob(pathname, recursive=recursive))
20071127162959.pdf          File "/usr/lib/python3.6/glob.py", line 55, in _iglob
20071127162959.pdf            yield from _glob1(dirname, basename, dironly)
20071127162959.pdf          File "/usr/lib/python3.6/glob.py", line 83, in _glob1
20071127162959.pdf            return fnmatch.filter(names, pattern)
20071127162959.pdf          File "/usr/lib/python3.6/fnmatch.py", line 52, in filter
20071127162959.pdf            match = _compile_pattern(pat)
20071127162959.pdf          File "/usr/lib/python3.6/fnmatch.py", line 46, in _compile_pattern
20071127162959.pdf            return re.compile(res).match
20071127162959.pdf          File "/usr/lib/python3.6/re.py", line 233, in compile
20071127162959.pdf            return _compile(pattern, flags)
20071127162959.pdf          File "/usr/lib/python3.6/re.py", line 301, in _compile
20071127162959.pdf            p = sre_compile.compile(pattern, flags)
20071127162959.pdf          File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
20071127162959.pdf            p = sre_parse.parse(p, flags)
20071127162959.pdf          File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
20071127162959.pdf            p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
20071127162959.pdf          File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
20071127162959.pdf            not nested and not items))
20071127162959.pdf          File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
20071127162959.pdf            p = _parse_sub(source, state, sub_verbose, nested + 1)
20071127162959.pdf          File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
20071127162959.pdf            not nested and not items))
20071127162959.pdf          File "/usr/lib/python3.6/sre_parse.py", line 553, in _parse
20071127162959.pdf            raise source.error(msg, len(this) + 1 + len(that))
20071127162959.pdf        sre_constants.error: bad character range Z-V at position 29
20071127162959.pdf
20071127162959.pdf
20071127162959.pdf      ERROR - RethrownJobError((None, None, <class 'sre_constants.error'>, error('bad character range Z-V at position 29',), 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 5840, in pipeline_run\n    for o_f_n in get_job_result_output_file_names(job_result):\n  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 5372, in get_job_result_output_file_names\n    for o_f_n in glob.glob(possible_glob_str):\n  File "/usr/lib/python3.6/glob.py", line 20, in glob\n    return list(iglob(pathname, recursive=recursive))\n  File "/usr/lib/python3.6/glob.py", line 55, in _iglob\n    yield from _glob1(dirname, basename, dironly)\n  File "/usr/lib/python3.6/glob.py", line 83, in _glob1\n    return fnmatch.filter(names, pattern)\n  File "/usr/lib/python3.6/fnmatch.py", line 52, in filter\n    match = _compile_pattern(pat)\n  File "/usr/lib/python3.6/fnmatch.py", line 46, in _compile_pattern\n    return re.compile(res).match\n  File "/usr/lib/python3.6/re.py", line 233, in compile\n    return _compile(pattern, flags)\n  File "/usr/lib/python3.6/re.py", line 301, in _compile\n    p = sre_compile.compile(pattern, flags)\n  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile\n    p = sre_parse.parse(p, flags)\n  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse\n    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)\n  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub\n    not nested and not items))\n  File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse\n    p = _parse_sub(source, state, sub_verbose, nested + 1)\n  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub\n    not nested and not items))\n  File "/usr/lib/python3.6/sre_parse.py", line 553, in _parse\n    raise source.error(msg, len(this) + 1 + len(that))\nsre_constants.error: bad character range Z-V at position 29\n'),)
```

**Comment by jbarlow83** [comment]
That release is over a year old (6.1.2) and the ruffus library in which the errors is going to be removed in the next release.

I suspect it has something to do with Ubuntu WSL, possibly the encoding of German characters, and the underlying filesystem being NTFS. If I had to guess, try renaming any files so that the names are pure ASCII only.

**Comment by flopes89** [comment]
Oh.... okay that version is the one I get when installing via apt... weird. Filenames are ascii only (as seen in the log).

I'll have a go with virtualbox, maybe it's a weird WSL thing...

**Comment by jbarlow83** [comment]
Yes 6.1.2 is what Ubuntu 18.04 ships. They snapshot all of the software they ship at the time the release is created and then apply security patches and bug fixes. As such, everything in Ubuntu 18.04 is over a year old. They do not accept new features.

There are Linuxes with continuously releases. You could also try Linuxbrew.
