### ISSUE TITLE
ocrmypdf not working, please help beginner

### ISSUE THREAD

**Issue by prankousky** [jbarlow83/OCRmyPDF#395]
Hi everybody,

I am running `Archlinux 5.1.5` with `Python 3.7.3` and `ocrmypdf 8.3.0`. Had `tesseract` installed already, but re-installed during the process (see below). `ocrmypdf` does not work; perhaps due to tesseract, but there is also an `No way to run job: Input file '/tmp/com.github.ocrmypdf.va1kb9nh/00001.text.pdf' does not exist` error, so I am not sure.

[THIS](https://de.scribd.com/document/412162819/Ocr-Test) is the document I used first, but other documents (that had OCR already) did not work, neither.

### First attemp

* installed `ocrmypdf` via `yay -S ocrmypdf`
* had `tesseract` installed already, plus its German and English language data
* because all my PDF files were searchable already (switched from OSX to Arch and my scanner automatically created searchable PDFs under OSX), I took a monochrome photo of something that was just on my desk and converted it to a PDF file (`convert test.jpg ocrtest.pdf`)
* ran `ocrmypdf ocrtest.pdf output.pdf`

Got this error:

```
  ERROR -    1: [tesseract] read_params_file: Can't open pdf
  ERROR -    1: [tesseract] read_params_file: Can't open txt
  ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
    job_history, verbose_abbreviated_path):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
    check_input_files_exist(*params)
  File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
    "Input file '%s' does not exist" % f)
ruffus.ruffus_exceptions.MissingInputFileError:


    No way to run job: Input file '/tmp/com.github.ocrmypdf.9cli9w43/000001.text.pdf' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 5364, in pipeline_run
    verbose)
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4729, in fill_queue_with_job_parameters
    for params in job_parameters:
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4669, in parameter_generator
    raise errt
ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions generating parameters for

    task = 'ocrmypdf._weave.weave_layers'

Original exception:

    Exception #1
      'ruffus.ruffus_exceptions.MissingInputFileError(


        No way to run job: Input file '/tmp/com.github.ocrmypdf.9cli9w43/000001.text.pdf' does not exist)' raised in ...
       Task = def ocrmypdf._weave.weave_layers(...):


    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
        job_history, verbose_abbreviated_path):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
        check_input_files_exist(*params)
      File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
        "Input file '%s' does not exist" % f)
    ruffus.ruffus_exceptions.MissingInputFileError:


        No way to run job: Input file '/tmp/com.github.ocrmypdf.9cli9w43/000001.text.pdf' does not exist
```

### Second attempt

* went to this github page (found out about this project from a blog and installed it right away via `yay`) and realized I should rather install it as described here `pip install ocrmypdf` (in Arch, python3 is standard, so I can use `pip install` instead of `pip3 install`afaik)
* deleted `tesseract` and all data plus any config files via `sudo pacman -Rns tesseract` 
* re-installed `tesseract` and **all** data packags via `sudo pacman -Syu tesseract` and  `yay -S tesseract-data` (which asked if I *really* wanted to install all data packages; "yes").
* `ocrmypdf ocrtest.pdf output.pdf` same error again
* tried a **different file**, that already had an OCR layer: `ocrmypdf something.pdf output.pdf` and got the following error
* `ERROR - 1 : page already has text!  - aborting (use --force-ocr to force OCR)`
* did just that

Got the following error

```
❯ ocrmypdf --force-ocr Schadengutachten\ RZ\ DC\ 59.pdf test.pdf
   INFO -    1: page already has text! - rasterizing text and running OCR anyway
   INFO -    2: page already has text! - rasterizing text and running OCR anyway
   INFO -    3: page already has text! - rasterizing text and running OCR anyway
   INFO -    4: page already has text! - rasterizing text and running OCR anyway
   INFO -    5: page already has text! - rasterizing text and running OCR anyway
   INFO -    6: page already has text! - rasterizing text and running OCR anyway
   INFO -    7: page already has text! - rasterizing text and running OCR anyway
   INFO -    8: page already has text! - rasterizing text and running OCR anyway
   INFO -    9: page already has text! - rasterizing text and running OCR anyway
   INFO -   10: page already has text! - rasterizing text and running OCR anyway
  ERROR -    4: [tesseract] read_params_file: Can't open pdf
  ERROR -    4: [tesseract] read_params_file: Can't open txt
  ERROR -    2: [tesseract] read_params_file: Can't open pdf
  ERROR -    2: [tesseract] read_params_file: Can't open txt
  ERROR -    7: [tesseract] read_params_file: Can't open pdf
  ERROR -    5: [tesseract] read_params_file: Can't open pdf
  ERROR -    5: [tesseract] read_params_file: Can't open txt
  ERROR -    7: [tesseract] read_params_file: Can't open txt
  ERROR -    6: [tesseract] read_params_file: Can't open pdf
  ERROR -    6: [tesseract] read_params_file: Can't open txt
  ERROR -    8: [tesseract] read_params_file: Can't open pdf
  ERROR -    8: [tesseract] read_params_file: Can't open txt
  ERROR -    1: [tesseract] read_params_file: Can't open pdf
  ERROR -    1: [tesseract] read_params_file: Can't open txt
  ERROR -   11: [tesseract] read_params_file: Can't open pdf
  ERROR -   11: [tesseract] read_params_file: Can't open txt
WARNING -   11: [tesseract] lots of diacritics - possibly poor OCR
  ERROR -    3: [tesseract] read_params_file: Can't open pdf
  ERROR -    3: [tesseract] read_params_file: Can't open txt
  ERROR -    9: [tesseract] read_params_file: Can't open pdf
  ERROR -    9: [tesseract] read_params_file: Can't open txt
  ERROR -   10: [tesseract] read_params_file: Can't open pdf
  ERROR -   10: [tesseract] read_params_file: Can't open txt
  ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
    job_history, verbose_abbreviated_path):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
    check_input_files_exist(*params)
  File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
    "Input file '%s' does not exist" % f)
ruffus.ruffus_exceptions.MissingInputFileError:


    No way to run job: Input file '/tmp/com.github.ocrmypdf.y936jhw_/000001.text.pdf' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 5364, in pipeline_run
    verbose)
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4729, in fill_queue_with_job_parameters
    for params in job_parameters:
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4669, in parameter_generator
    raise errt
ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions generating parameters for

    task = 'ocrmypdf._weave.weave_layers'

Original exception:

    Exception #1
      'ruffus.ruffus_exceptions.MissingInputFileError(


        No way to run job: Input file '/tmp/com.github.ocrmypdf.y936jhw_/000001.text.pdf' does not exist)' raised in ...
       Task = def ocrmypdf._weave.weave_layers(...):


    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
        job_history, verbose_abbreviated_path):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
        check_input_files_exist(*params)
      File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
        "Input file '%s' does not exist" % f)
    ruffus.ruffus_exceptions.MissingInputFileError:


        No way to run job: Input file '/tmp/com.github.ocrmypdf.y936jhw_/000001.text.pdf' does not exist

```

What can I do to fix this? My goal is to save all my scans (which will not have OCR already because my scanner only supports this when using Windows or Mac) to a particular folder, i.e. `~/Documents/scans/incoming` and have a watchdog monitor this directory. Any new PDF file is supposed to be OCRed automatically and send to something like `~/Documents/scans/ocr`.

Do I need to install anything on top of those packages I already have? Or how can I make this work?

Thanks in advance for your help :)

**Comment by jbarlow83** [comment]
This seems to be a problem with how Tesseract is installed and/or the `TESSDATA_PREFIX` environment variable. The messages like...
```
ERROR -    8: [tesseract] read_params_file: Can't open pdf
```

mean that there is file that should be named something like `/usr/share/tessdata/configs/pdf` and the file was not found. As such, Tesseract fails, and ocrmypdf is complaining that it can't find the file it expected Tesseract to create.

You'll want to confirm that you can run Tesseract on an image, as explained in that project's documentation. You can also run `ocrmypdf -k -v 1` and the resulting output will leave the temporary files intact (`-k`) and also print exactly what commands it was running (`-v 1`). You can try to repeat the command line manually.

**Comment by prankousky** [comment]
Thank you @jbarlow83 .

I set the `TESSDATA_PREFIX` accordingly. And also tried running it on an image like this `ocrmypdf ocrtest.jpg -l deu test.pdf`. This will then generate the following output


```
❯ ocrmypdf ocrtest.jpg -l deu teest.pdf
   INFO - Input file is not a PDF, checking if it is an image...
   INFO - Input file is an image
   INFO - Input image has no ICC profile, assuming sRGB
   INFO - Image seems valid. Try converting to PDF...
   INFO - Successfully converted to PDF, processing...
  ERROR -    1: [tesseract] read_params_file: Can't open pdf
  ERROR -    1: [tesseract] read_params_file: Can't open txt
  ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
    job_history, verbose_abbreviated_path):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
    check_input_files_exist(*params)
  File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
    "Input file '%s' does not exist" % f)
ruffus.ruffus_exceptions.MissingInputFileError:


    No way to run job: Input file '/tmp/com.github.ocrmypdf.hymuxtiz/000001.text.pdf' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 5364, in pipeline_run
    verbose)
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4729, in fill_queue_with_job_parameters
    for params in job_parameters:
  File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4669, in parameter_generator
    raise errt
ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions generating parameters for

    task = 'ocrmypdf._weave.weave_layers'

Original exception:

    Exception #1
      'ruffus.ruffus_exceptions.MissingInputFileError(


        No way to run job: Input file '/tmp/com.github.ocrmypdf.hymuxtiz/000001.text.pdf' does not exist)' raised in ...
       Task = def ocrmypdf._weave.weave_layers(...):


    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
        job_history, verbose_abbreviated_path):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
        check_input_files_exist(*params)
      File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
        "Input file '%s' does not exist" % f)
    ruffus.ruffus_exceptions.MissingInputFileError:


        No way to run job: Input file '/tmp/com.github.ocrmypdf.hymuxtiz/000001.text.pdf' does not exist

```

When I run the command you gave, I get this output 

```
❯ ocrmypdf -k -v 1 ocrtest.jpg -l deu test.pdf
  DEBUG - ocrmypdf 8.3.0
  DEBUG - Found tesseract 5.0.0-alpha-150-g5e62
  DEBUG - Found gs 9.27
  DEBUG - Found qpdf 8.4.2
  DEBUG - os.symlink(ocrtest.jpg, /tmp/com.github.ocrmypdf.kjp5cr32/origin)

________________________________________
Tasks which will be run:


Task enters queue = 'ocrmypdf._pipeline.triage'
   INFO - Input file is not a PDF, checking if it is an image...
   INFO - Input file is an image
   INFO - Input image has no ICC profile, assuming sRGB
   INFO - Image seems valid. Try converting to PDF...
   INFO - Successfully converted to PDF, processing...
Completed Task = 'ocrmypdf._pipeline.triage'
Task enters queue = 'ocrmypdf._pipeline.repair_and_parse_pdf'
  DEBUG - <PdfInfo('...'), page count=1>
Completed Task = 'ocrmypdf._pipeline.repair_and_parse_pdf'
Task enters queue = 'ocrmypdf._pipeline.marker_pages'
Task enters queue = 'ocrmypdf._pipeline.generate_postscript_stub'
Completed Task = 'ocrmypdf._pipeline.marker_pages'
Task enters queue = 'ocrmypdf._pipeline.ocr_or_skip'
Completed Task = 'ocrmypdf._pipeline.generate_postscript_stub'
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.kjp5cr32/000001.marker.pdf, /tmp/com.github.ocrmypdf.kjp5cr32/000001.ocr.page.pdf)
Completed Task = 'ocrmypdf._pipeline.ocr_or_skip'
Task enters queue = 'ocrmypdf._pipeline.orient_page'
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.kjp5cr32/000001.ocr.page.pdf, /tmp/com.github.ocrmypdf.kjp5cr32/000001.ocr.oriented.pdf)
Completed Task = 'ocrmypdf._pipeline.orient_page'
Task enters queue = 'ocrmypdf._pipeline.rasterize_with_ghostscript'
  DEBUG - Rasterize 000001.ocr.oriented.pdf with png16m
  DEBUG - ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r133.000012x133.000012', '-o', '/tmp/tmphwrm7d24', '-dAutoRotatePages=/None', '-f', '/tmp/com.github.ocrmypdf.kjp5cr32/000001.ocr.oriented.pdf']
  DEBUG -
  DEBUG - Rotating output by 0
Completed Task = 'ocrmypdf._pipeline.rasterize_with_ghostscript'
Task enters queue = 'ocrmypdf._pipeline.preprocess_remove_background'
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.kjp5cr32/000001.page.png, /tmp/com.github.ocrmypdf.kjp5cr32/000001.pp-background.png)
Completed Task = 'ocrmypdf._pipeline.preprocess_remove_background'
Task enters queue = 'ocrmypdf._pipeline.preprocess_deskew'
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.kjp5cr32/000001.pp-background.png, /tmp/com.github.ocrmypdf.kjp5cr32/000001.pp-deskew.png)
Completed Task = 'ocrmypdf._pipeline.preprocess_deskew'
Task enters queue = 'ocrmypdf._pipeline.preprocess_clean'
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.kjp5cr32/000001.pp-deskew.png, /tmp/com.github.ocrmypdf.kjp5cr32/000001.pp-clean.png)
Completed Task = 'ocrmypdf._pipeline.preprocess_clean'
Task enters queue = 'ocrmypdf._pipeline.select_ocr_image'
Task enters queue = 'ocrmypdf._pipeline.select_visible_page_image'
  DEBUG - resolution 133 133
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.kjp5cr32/000001.page.png, /tmp/com.github.ocrmypdf.kjp5cr32/000001.image)
Completed Task = 'ocrmypdf._pipeline.select_visible_page_image'
Task enters queue = 'ocrmypdf._pipeline.select_image_layer'
Completed Task = 'ocrmypdf._pipeline.select_ocr_image'
Task enters queue = 'ocrmypdf._pipeline.ocr_tesseract_textonly_pdf'
  DEBUG -    1: page eligible for lossless reconstruction
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.kjp5cr32/000001.ocr.oriented.pdf, /tmp/com.github.ocrmypdf.kjp5cr32/000001.image-layer.pdf)
Completed Task = 'ocrmypdf._pipeline.select_image_layer'
  DEBUG - ['tesseract', '-l', 'deu', '-c', 'textonly_pdf=1', '/tmp/com.github.ocrmypdf.kjp5cr32/000001.ocr.png', '/tmp/com.github.ocrmypdf.kjp5cr32/000001.text', 'pdf', 'txt']
  ERROR -    1: [tesseract] read_params_file: Can't open pdf
  ERROR -    1: [tesseract] read_params_file: Can't open txt
Completed Task = 'ocrmypdf._pipeline.ocr_tesseract_textonly_pdf'
Task enters queue = 'ocrmypdf._weave.weave_layers'
  DEBUG -



Original exception:

    Exception #1
      '<class 'ruffus.ruffus_exceptions.RethrownJobError'>

        Exceptions generating parameters for

        task = 'ocrmypdf._weave.weave_layers'

    Original exception:

        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(


            No way to run job: Input file '/tmp/com.github.ocrmypdf.kjp5cr32/000001.text.pdf' does not exist)' raised in ...
           Task = def ocrmypdf._weave.weave_layers(...):


        Traceback (most recent call last):
          File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
            check_input_files_exist(*params)
          File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        ruffus.ruffus_exceptions.MissingInputFileError:


            No way to run job: Input file '/tmp/com.github.ocrmypdf.kjp5cr32/000001.text.pdf' does not exist

        ' raised in ...
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
        job_history, verbose_abbreviated_path):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
        check_input_files_exist(*params)
      File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
        "Input file '%s' does not exist" % f)
    ruffus.ruffus_exceptions.MissingInputFileError:


        No way to run job: Input file '/tmp/com.github.ocrmypdf.kjp5cr32/000001.text.pdf' does not exist

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 5364, in pipeline_run
        verbose)
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4729, in fill_queue_with_job_parameters
        for params in job_parameters:
      File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4669, in parameter_generator
        raise errt
    ruffus.ruffus_exceptions.RethrownJobError:

        Exceptions generating parameters for

        task = 'ocrmypdf._weave.weave_layers'

    Original exception:

        Exception #1
          'ruffus.ruffus_exceptions.MissingInputFileError(


            No way to run job: Input file '/tmp/com.github.ocrmypdf.kjp5cr32/000001.text.pdf' does not exist)' raised in ...
           Task = def ocrmypdf._weave.weave_layers(...):


        Traceback (most recent call last):
          File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4569, in parameter_generator
            job_history, verbose_abbreviated_path):
          File "/usr/lib/python3.7/site-packages/ruffus/task.py", line 4408, in job_needs_to_run
            check_input_files_exist(*params)
          File "/usr/lib/python3.7/site-packages/ruffus/file_name_parameters.py", line 382, in check_input_files_exist
            "Input file '%s' does not exist" % f)
        ruffus.ruffus_exceptions.MissingInputFileError:


            No way to run job: Input file '/tmp/com.github.ocrmypdf.kjp5cr32/000001.text.pdf' does not exist




Temporary working files saved at:
/tmp/com.github.ocrmypdf.kjp5cr32

```

and 

```
 ls /tmp/com.github.ocrmypdf.kjp5cr32
  000001.image              000001.ocr.oriented.pdf    000001.page.png             000001.pp-deskew.png    origin.pdf             ruffus_history.sqlite
  000001.image-layer.pdf    000001.ocr.page.pdf        000001.pp-background.png    000001.text.txt         origin.repaired.pdf
  000001.marker.pdf         000001.ocr.png             000001.pp-clean.png         origin                  pdfa.ps
```

All png files in that directory *look* the same when opened in sxiv. `00001.text.txt` contains the text from the jpg file used as input. All pdf files look the same as well; I opened each one in `zathura` and tried selecting some text, but none of those files were searchable.

The ps file contains


```
%!
% Define entries in the document Info dictionary :
/ICCProfile <2f7573722f6c69622f707974686f6e332e372f736974652d7061636b616765732f6f63726d797064662f646174612f735247422e696363>
def

% Define an ICC profile :

[/_objdef {icc_PDFA} /type /stream /OBJ pdfmark
[{icc_PDFA}
<<
  /N currentpagedevice /ProcessColorModel known {
    currentpagedevice /ProcessColorModel get dup /DeviceGray eq
    {pop 1} {
      /DeviceRGB eq
      {3}{4} ifelse
    } ifelse
  } {
    (ERROR, unable to determine ProcessColorModel) == flush
  } ifelse
>> /PUT pdfmark
[{icc_PDFA} ICCProfile (r) file /PUT pdfmark

% Define the output intent dictionary :

[/_objdef {OutputIntent_PDFA} /type /dict /OBJ pdfmark
[{OutputIntent_PDFA} <<
  /Type /OutputIntent             % Must be so (the standard requires).
  /S /GTS_PDFA1                   % Must be so (the standard requires).
  /DestOutputProfile {icc_PDFA}            % Must be so (see above).
  /OutputConditionIdentifier (sRGB)
>> /PUT pdfmark
[{Catalog} <</OutputIntents [ {OutputIntent_PDFA} ]>> /PUT pdfmark

```

The debug output doesn't seem to have a problem with txt and pdf; I copied *all* files from `/usr/share/tessdata/` to my previous `TESSDATA_PREFIX` directory, so they are definitely there. I then changed the directory to /usr/share/... and reloaded my env variables, so that it would read the original files that came with my install of tesseract for sure. Still the same output.

Can you tell what might be the problem here? I will run each command from debug manually after posting this; if I find out anything new, I will add it to this post (and if I don't ifnd anything new I'll wait for your reply).

**Comment by jbarlow83** [comment]
This is the exact command that failed (as a Python list rather than space-separated command line)
```
'tesseract', '-l', 'deu', '-c', 'textonly_pdf=1', '/tmp/com.github.ocrmypdf.kjp5cr32/000001.ocr.png', '/tmp/com.github.ocrmypdf.kjp5cr32/000001.text', 'pdf', 'txt'
```

The error message relays what Tesseract reported:
```
ERROR -    1: [tesseract] read_params_file: Can't open pdf
  ERROR -    1: [tesseract] read_params_file: Can't open txt
```

That means `tessdata/configs/pdf` and `tessdata/configs/txt` could not be found in the tessdata folder. (These are short text files that configure Tessearct.)
