### ISSUE TITLE
Error when trying to OCR JPEG or PNG

### ISSUE THREAD

**Issue by shaunc869** [jbarlow83/OCRmyPDF#42]
When I try to run: 

    sudo ocrmypdf --verbose 3 eiffel.jpg eiffel.pdf

I get:

    Original exception:
    Exception #1
      'builtins.TypeError(Can't convert 'list' object to str implicitly)' raised in ...
       Task = def ocrmypdf.main.split_pages(...):
       Job  = [[] -> .../com.github.ocrmypdf.45n_qza7/*.page.pdf, <ocrmypdf.main.WrappedLogger>, [], <_thread.lock>]
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/usr/local/lib/python3.4/dist-packages/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/usr/local/lib/python3.4/dist-packages/ocrmypdf/main.py", line 415, in split_pages
        npages = qpdf.get_npages(input_file)
      File "/usr/local/lib/python3.4/dist-packages/ocrmypdf/qpdf.py", line 68, in get_npages
        universal_newlines=True, close_fds=True)
      File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
        with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
      File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
        restore_signals, start_new_session, preexec_fn)
    TypeError: Can't convert 'list' object to str implicitly

If I try the same thing on a PDF file it works fine. This is for version 3.1.1, thanks!

I can repeat the bug on both Mac OS X El Capitan and Debian 8, I can also repeat the error in version 3.1 and 3.0.

The file in question is here (yes I know there isn't any text I was just using it for testing):

![eiffel](https://cloud.githubusercontent.com/assets/6071090/12279974/809281ea-b93f-11e5-91c1-a4b3a5112aae.jpg)

**Comment by jbarlow83** [comment]
Only PDF input is supported for now.

img2pdf does a good job at converting most JPEGs and PNGs to PDF.
And yes, that's a really crappy error message, which I should fix.

**Comment by jbarlow83** [comment]
Next release fixes the error message.

By the way, there should be no need to `sudo ocrmypdf`. You don't have to trust me with root access to your system.
