### ISSUE TITLE
close_fds is not supported on Windows platforms...

### ISSUE THREAD

**Issue by cealvara** [jbarlow83/OCRmyPDF#44]
Hi,

I'm getting this error 

> [Anaconda3] C:\Users\Carlos\Anaconda3>ocrmypdf --help
Traceback (most recent call last):
  File "C:\Users\Carlos\Anaconda3\Scripts\ocrmypdf-script.py", line 9, in <module>
    load_entry_point('ocrmypdf==3.1.1', 'console_scripts', 'ocrmypdf')()
  File "C:\Users\Carlos\Anaconda3\lib\site-packages\setuptools-19.4-py3.5.egg\pkg_resources\__init__.py", line 549, in load_entry_point
  File "C:\Users\Carlos\Anaconda3\lib\site-packages\setuptools-19.4-py3.5.egg\pkg_resources\__init__.py", line 2709, in load_entry_point
  File "C:\Users\Carlos\Anaconda3\lib\site-packages\setuptools-19.4-py3.5.egg\pkg_resources\__init__.py", line 2369, in load
  File "C:\Users\Carlos\Anaconda3\lib\site-packages\setuptools-19.4-py3.5.egg\pkg_resources\__init__.py", line 2375, in resolve
  File "C:\Users\Carlos\Anaconda3\lib\site-packages\ocrmypdf-3.1.1-py3.5.egg\ocrmypdf\main.py", line 51, in <module>
    if tesseract.version() < MINIMUM_TESS_VERSION:
  File "C:\Users\Carlos\Anaconda3\lib\site-packages\ocrmypdf-3.1.1-py3.5.egg\ocrmypdf\tesseract.py", line 51, in version
    stderr=STDOUT)
  File "C:\Users\Carlos\Anaconda3\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "C:\Users\Carlos\Anaconda3\lib\subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Carlos\Anaconda3\lib\subprocess.py", line 873, in __init__
    "close_fds is not supported on Windows platforms"
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

Thank you for your help.

**Comment by jbarlow83** [comment]
Oh, that's just the tip of the iceberg of trouble trying to get it to work on Windows. :) There are some dependencies that are probably not compatible or have significant differences.

To use it on Windows, install Docker and pull the docker version (that will give you a lightweight virtual machine) -- see instructions in the README.
