### ISSUE TITLE
pdfminer.six version issue

### ISSUE THREAD

**Issue by Raymo111** [jbarlow83/OCRmyPDF#457]
**Describe the issue**
Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pdfminer.six 20191110 (/usr/lib/python3.8/site-packages), Requirement.parse('pdfminer.six<=20191020,>=20181108'), {'ocrmypdf'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pdfminer.six<=20191020,>=20181108' distribution was not found and is required by ocrmypdf
```

**To Reproduce**
```bash
ocrmypdf  anything
```

**Expected behavior**
It should just work.

**System:**
- OS: Arch Linux 5.3.12-arch1-1
- OCRmyPDF Version: 9.0.5-1

**Additional context**
I have version 20191110-1 of pdfminer.six installed. This is the issue. The AUR package has already been marked as Out-of-date.

**Comment by jbarlow83** [comment]
This is fixed in 9.1.1. Hopefully Arch will update soon!
