### ISSUE TITLE
RecursionError - 000447.pdf [/V/T/]

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#459]
```
Traceback (most recent call last):
  File "/Users/jb/src/geoocr/src/ocrmypdf/_sync.py", line 390, in run_pipeline
    progbar=options.progress_bar,
  File "/Users/jb/src/geoocr/src/ocrmypdf/_pipeline.py", line 150, in get_pdfinfo
    input_file, detailed_page_analysis=detailed_page_analysis, progbar=progbar
  File "/Users/jb/src/geoocr/src/ocrmypdf/pdfinfo/info.py", line 754, in __init__
    infile, detailed_page_analysis, log=log, progbar=progbar
  File "/Users/jb/src/geoocr/src/ocrmypdf/pdfinfo/info.py", line 631, in _pdf_get_all_pageinfo
    page = PageInfo(pdf, n, infile, page_xml, detailed_analysis)
  File "/Users/jb/src/geoocr/src/ocrmypdf/pdfinfo/info.py", line 641, in __init__
    self._pageinfo = _pdf_get_pageinfo(pdf, pageno, infile, xmltext)
  File "/Users/jb/src/geoocr/src/ocrmypdf/pdfinfo/info.py", line 571, in _pdf_get_pageinfo
    miner = get_page_analysis(infile, pageno, pscript5_mode)
  File "/Users/jb/src/geoocr/src/ocrmypdf/pdfinfo/layout.py", line 288, in get_page_analysis
    interp.process_page(next(page))
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 852, in process_page
    self.device.end_page(page)
  File "/Users/jb/src/geoocr/src/ocrmypdf/pdfinfo/layout.py", line 225, in end_page
    self.cur_item.analyze(self.laparams)
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/layout.py", line 719, in analyze
    group.analyze(laparams)
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/layout.py", line 497, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/layout.py", line 347, in analyze
    obj.analyze(laparams)
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/layout.py", line 497, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/layout.py", line 347, in analyze
    obj.analyze(laparams)
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/layout.py", line 497, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/Users/jb/src/geoocr/.venv/lib/python3.7/site-packages/pdfminer/layout.py", line 347, in analyze
    obj.analyze(laparams)
...repeats...
```

**Comment by jbarlow83** [comment]
Sounds very much like https://github.com/pdfminer/pdfminer.six/pull/335

so resolved in pdfminer
