### ISSUE TITLE
XML Syntax Error

### ISSUE THREAD

**Issue by jjeffrey** [jbarlow83/OCRmyPDF#476]
**Describe the issue**
When running OCR on a PDF, I am consistently getting a fatal error that prevents completion.

I ran
```bash
ocrmypdf   feynman_in.pdf feynman_out.pdf
```
and the following occurred:

```
   INFO - Start processing 8 pages concurrent
WARNING -    2: [tesseract] lots of diacritics - possibly poor OCR
  ERROR - An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 304, in _load_from
    self._xmp = parse(BytesIO(data))
  File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1856, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 8
lxml.etree.XMLSyntaxError: xmlParseCharRef: invalid xmlChar value 8, line 8, column 22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 308, in _load_from
    self._xmp = parse(BytesIO(data))
  File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1856, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 8
lxml.etree.XMLSyntaxError: xmlParseCharRef: invalid xmlChar value 8, line 8, column 22

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 338, in run_pipeline
    exec_concurrent(context)
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 295, in exec_concurrent
    pdf = post_process(pdf, context)
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 175, in post_process
    pdf_out = metadata_fixup(pdf_out, context)
  File "/usr/lib/python3/dist-packages/ocrmypdf/_pipeline.py", line 731, in metadata_fixup
    with pdf.open_metadata() as meta:
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 198, in wrapper
    self._load()
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 300, in _load
    self._load_from(data)
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 310, in _load_from
    raise PdfError() from e
pikepdf._qpdf.PdfError

```

**To Reproduce**
I was attempting to run OCR on an input PDF. I have successfully done OCR on other PDFs before, so something about this one
[There is Plenty of Room at The Bottom (1960) Feynman_ENGINEEERING and Science  CALTECH .pdf](https://github.com/jbarlow83/OCRmyPDF/files/4052148/There.is.Plenty.of.Room.at.The.Bottom.1960.Feynman_ENGINEEERING.and.Science.CALTECH.pdf) trips the program up for me.

The command I used was:

```bash
ocrmypdf   feynman_in.pdf feynman_out.pdf
```

**Example file**
[There is Plenty of Room at The Bottom (1960) Feynman_ENGINEEERING and Science  CALTECH .pdf](https://github.com/jbarlow83/OCRmyPDF/files/4052150/There.is.Plenty.of.Room.at.The.Bottom.1960.Feynman_ENGINEEERING.and.Science.CALTECH.pdf)

- [x] This is the input file
- [x] The file contains no personal or confidential information
- [x] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

**Expected behavior**
A clear and concise description of what you expected to happen. Include screenshots if applicable.

**System:**

- OS: Ubuntu 19.10
- OCRmyPDF Version: 9.0.3+dfsg

**Comment by jbarlow83** [comment]
In the DocumentInfo dictionary, the /Creator of the file was set to garbage data, in this case just the backspace control code. Ghostscript (as it should) copies the Creator to the XMP metadata value `<xmp:CreatorTool>`, producing invalid XML.

You can work around this by editing the PDF metadata to correct the issue. One way to do that is pikepdf:

```python
p = pikepdf.open('file.pdf')
del p.docinfo.Creator
p.save('fixed file.pdf')
```

That will be faster than waiting for me to fix it.

**Comment by jbarlow83** [comment]
This needs to be fixed in ocrmypdf and pikepdf. ocrmypdf should check that docinfo values are safe. pikepdf could learn to fix problems like this. 

Could also report to Ghostscript which currently takes a garbage in/garbage out approach.

**Comment by blubbsy** [comment]
do you need more input files? i think i'm getting the same error.

**Comment by jbarlow83** [comment]
As of pikepdf >= v1.10.0 this should be fixed. Note it will delete some of the corrupt metadata.

I doubt Ubuntu would be interested in a backport for this fix; you will have to install a newer version of ocrmypdf manually to get it. The procedure is in the installation manual.

**Comment by jbarlow83** [comment]
Fixed with newer pikepdf versions
