### ISSUE TITLE
ocrmypdf does not work with Alfresco 'ocr action'

### ISSUE THREAD

**Issue by Ikkache27** [jbarlow83/OCRmyPDF#478]
Hello @jbarlow83
I have this issue ... i'm using Ocrmypdf with alfresco ... Ocrmypdf work well manually using the command ... but when I use it with alfresco 'OCR action' does'nt work ... this is the log :
```
Caused by: java.lang.RuntimeException: org.alfresco.service.cmr.repository.ContentIOException: 000817996 Failed to perform OCR transformation:
Execution result:
os: Linux
command: /usr/local/bin/ocrmypdf --verbose 1 --force-ocr -l eng /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4887267237326407155.pdf /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4887267237326407155_ocr.pdf
succeeded: false
exit code: 1
out:
err: Traceback (most recent call last):
File "/usr/local/bin/ocrmypdf", line 5, in
from ocrmypdf.main import run
File "/root/.local/lib/python3.6/site-packages/ocrmypdf/init.py", line 20, in
from .api import Verbosity
at es.keensoft.alfresco.ocr.OCRExtractAction.executeImplInternal(OCRExtractAction.java:183)
at es.keensoft.alfresco.ocr.OCRExtractAction.access$200(OCRExtractAction.java:38)
at es.keensoft.alfresco.ocr.OCRExtractAction$1.execute(OCRExtractAction.java:164)
at es.keensoft.alfresco.ocr.OCRExtractAction$1.execute(OCRExtractAction.java:161)
at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
at es.keensoft.alfresco.ocr.OCRExtractAction.executeInNewTransaction(OCRExtractAction.java:169)
at es.keensoft.alfresco.ocr.OCRExtractAction.access$100(OCRExtractAction.java:38)
at es.keensoft.alfresco.ocr.OCRExtractAction$ExtractOCRTask.run(OCRExtractAction.java:151)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```
thankx for your help

**Comment by jbarlow83** [comment]
It looks like you originally installed with `pip install ocrmypdf` as root, and then later upgraded using `pip install --user ocrmypdf` or something along those lines. However it came about, the version of `/usr/local/bin/ocrmypdf` does not match the version of ocrmypdf installed at `../site-packages/ocrmypdf`. 

It might work to explicitly execute `/root/.local/bin/ocrmypdf` instead. 

Alternately, manually delete the bin/ script, then use pip to remove and reinstall ocrmypdf, and confirm that it works independently of Alfresco.

**Comment by Ikkache27** [comment]
Dear @jbarlow83 , thanx for your reply.

The poblem persist ...  I have deleted the /bin script and remove then reinstall ocrmypdf using pip ... this command **worked well manually** : command:    /usr/local/bin/ocrmypdf --verbose 1 --force-ocr -l eng /opt/alfresco-community/tomcat/temp/Alfresco /OCRTransformWorker_source_8699565729729916770.pdf /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_8699565729729916770_ocr.pdf

But i get this error when I launch the **'ocr action' from Alfresco** :

Exception in thread "defaultAsyncAction1" java.lang.RuntimeException: java.lang.RuntimeException: org.alfresco.service.cmr.repository.ContentIOException: 00140041 Failed to perform OCR transformation:
Execution result:
   os:         Linux
   command:    /usr/local/bin/ocrmypdf --verbose 1 --force-ocr -l eng /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_8699565729729916770.pdf /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_8699565729729916770_ocr.pdf
   succeeded:  false
   exit code:  1
   out:
   err:        Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/__init__.py", line 20, in <module>
    from .api import Verbosity,
        at es.keensoft.alfresco.ocr.OCRExtractAction.executeImplInternal(OCRExtractAction.java:183)
        at es.keensoft.alfresco.ocr.OCRExtractAction.access$200(OCRExtractAction.java:38)
        at es.keensoft.alfresco.ocr.OCRExtractAction$1.execute(OCRExtractAction.java:164)
        at es.keensoft.alfresco.ocr.OCRExtractAction$1.execute(OCRExtractAction.java:161)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
        at es.keensoft.alfresco.ocr.OCRExtractAction.executeInNewTransaction(OCRExtractAction.java:169)
        at es.keensoft.alfresco.ocr.OCRExtractAction.access$100(OCRExtractAction.java:38)
        at es.keensoft.alfresco.ocr.OCRExtractAction$ExtractOCRTask.run(OCRExtractAction.java:151)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jbarlow83** [comment]
If ocrmypdf works well manually the issue must be with Alfresco.

**Comment by Ikkache27** [comment]
Hi @jbarlow83 
I figured out a configuration that works now. I added **sudo** to ocr command in alfresco-golobal.propreties :
ocr.command=sudo /usr/local/bin/ocrmypdf

thank you for your help, highly appreciated
