### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#51]
I just wanted to install 4.0.1 but had unfortunately no success.
Have you got a clue how to align the ducks?
```

>$ sudo pip3 install git+https://github.com/jbarlow83/OCRmyPDF.git
Downloading/unpacking git+https://github.com/jbarlow83/OCRmyPDF.git
  Cloning https://github.com/jbarlow83/OCRmyPDF.git to /tmp/pip-jyrz2gnr-build
  Running setup.py (path:/tmp/pip-jyrz2gnr-build/setup.py) egg_info for package from git+https://github.com/jbarlow83/OCRmyPDF.git
    
    Installed /tmp/easy_install-y2a_jcj5/pytest-runner-2.7/.eggs/setuptools_scm-1.10.1-py3.4.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-jyrz2gnr-build/.eggs/pytest_runner-2.7-py3.4.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-jyrz2gnr-build/setup.py", line 235, in <module>
        zip_safe=False)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1074, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 711, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (cffi 1.1.2 (/usr/lib/python3/dist-packages), Requirement.parse('cffi>=1.5.0'))
    Complete output from command python setup.py egg_info:
    

Installed /tmp/easy_install-y2a_jcj5/pytest-runner-2.7/.eggs/setuptools_scm-1.10.1-py3.4.egg

zip_safe flag not set; analyzing archive contents...



Installed /tmp/pip-jyrz2gnr-build/.eggs/pytest_runner-2.7-py3.4.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-jyrz2gnr-build/setup.py", line 235, in <module>

    zip_safe=False)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 268, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 836, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1074, in best_match

    dist = working_set.find(req)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 711, in find

    raise VersionConflict(dist, req)

pkg_resources.VersionConflict: (cffi 1.1.2 (/usr/lib/python3/dist-packages), Requirement.parse('cffi>=1.5.0'))

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-jyrz2gnr-build
Storing debug log for failure in /home/xxx/.pip/pip.log
```

The mentioned pip.log file says:

```
------------------------------------------------------------
/usr/bin/pip3 run on Thu Feb 18 12:14:54 2016
Downloading/unpacking git+https://github.com/jbarlow83/OCRmyPDF.git
  Cloning https://github.com/jbarlow83/OCRmyPDF.git to /tmp/pip-jyrz2gnr-build
  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q https://github.com/jbarlow83/OCRmyPDF.git /tmp/pip-jyrz2gnr-build
  Running setup.py (path:/tmp/pip-jyrz2gnr-build/setup.py) egg_info for package from git+https://github.com/jbarlow83/OCRmyPDF.git
    
    Installed /tmp/easy_install-y2a_jcj5/pytest-runner-2.7/.eggs/setuptools_scm-1.10.1-py3.4.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-jyrz2gnr-build/.eggs/pytest_runner-2.7-py3.4.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-jyrz2gnr-build/setup.py", line 235, in <module>
        zip_safe=False)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1074, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 711, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (cffi 1.1.2 (/usr/lib/python3/dist-packages), Requirement.parse('cffi>=1.5.0'))
    Complete output from command python setup.py egg_info:
    

Installed /tmp/easy_install-y2a_jcj5/pytest-runner-2.7/.eggs/setuptools_scm-1.10.1-py3.4.egg

zip_safe flag not set; analyzing archive contents...



Installed /tmp/pip-jyrz2gnr-build/.eggs/pytest_runner-2.7-py3.4.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-jyrz2gnr-build/setup.py", line 235, in <module>

    zip_safe=False)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 268, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 836, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1074, in best_match

    dist = working_set.find(req)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 711, in find

    raise VersionConflict(dist, req)

pkg_resources.VersionConflict: (cffi 1.1.2 (/usr/lib/python3/dist-packages), Requirement.parse('cffi>=1.5.0'))

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-jyrz2gnr-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-jyrz2gnr-build
```

**Comment by jbarlow83** [comment]
You seem to have the worst luck with this.

What does 'sudo pip3 install ocrmypdf' do? Did that not work?

You don't normally need to mention git to pip unless you want a specific
development version.

**Comment by femifrak** [comment]
'sudo pip3 install ocrmypdf' results in:

Does it tell you something?

```
Downloading/unpacking ocrmypdf
  Downloading ocrmypdf-4.0.1-py34-none-any.whl
Downloading/unpacking cffi>=1.5.0 (from ocrmypdf)
  Downloading cffi-1.5.2.tar.gz (388kB): 388kB downloaded
  Running setup.py (path:/tmp/pip-build-5meupng1/cffi/setup.py) egg_info for package cffi
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    
Requirement already satisfied (use --upgrade to upgrade): img2pdf>=0.2.0 in /usr/local/lib/python3.4/dist-packages (from ocrmypdf)
Requirement already satisfied (use --upgrade to upgrade): reportlab>=3.1.44 in /usr/lib/python3/dist-packages (from ocrmypdf)
Requirement already satisfied (use --upgrade to upgrade): ruffus>=2.6.3 in /home/tho/.local/lib/python3.4/site-packages (from ocrmypdf)
Downloading/unpacking Pillow>=3.0.0 (from ocrmypdf)
  Downloading Pillow-3.1.1.tar.gz (10.1MB): 10.1MB downloaded
  Running setup.py (path:/tmp/pip-build-5meupng1/Pillow/setup.py) egg_info for package Pillow
    
    warning: no previously-included files found matching '.editorconfig'
Requirement already satisfied (use --upgrade to upgrade): PyPDF2>=1.25.1 in /usr/local/lib/python3.4/dist-packages (from ocrmypdf)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python3/dist-packages (from cffi>=1.5.0->ocrmypdf)
Installing collected packages: ocrmypdf, cffi, Pillow
  Found existing installation: cffi 1.1.2
    Not uninstalling cffi at /usr/lib/python3/dist-packages, owned by OS
  Running setup.py install for cffi
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.4/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: Datei oder Verzeichnis nicht gefunden
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-5meupng1/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-27vwjquo-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-3.4

creating build/lib.linux-x86_64-3.4/cffi

copying cffi/gc_weakref.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/model.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/verifier.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/recompiler.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/cparser.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/api.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/__init__.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/commontypes.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/lock.py -> build/lib.linux-x86_64-3.4/cffi

copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.4/cffi

copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.4/cffi

copying cffi/_embedding.h -> build/lib.linux-x86_64-3.4/cffi

running build_ext

building '_cffi_backend' extension

creating build/temp.linux-x86_64-3.4

creating build/temp.linux-x86_64-3.4/c

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.4/c/_cffi_backend.o

c/_cffi_backend.c:15:17: fatal error: ffi.h: Datei oder Verzeichnis nicht gefunden

compilation terminated.with pip.log:

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Can't roll back cffi; was not uninstalled
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-5meupng1/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-27vwjquo-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-5meupng1/cffi
Storing debug log for failure in /home/xxx/.pip/pip.log
```

**Comment by femifrak** [comment]
sorry for bothering. Now ocrmypdf runs perfectly. I don't know why, maybe it ran before and I was only mislead by the error message, or maybe because I installed the development files of libffi.

Thanks a lot for your great job!


(I still have a disconcerting tail of pip.log:)
```
 Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-di61k1yp/Pillow/setup.py", line 767, in <module>

    zip_safe=not debug_build(),

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run

    self.run_command('build')

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run

    self.run_command(cmd_name)

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run

    self.build_extensions()

  File "/tmp/pip-build-di61k1yp/Pillow/setup.py", line 516, in build_extensions

    (f, f))

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

----------------------------------------
  Can't roll back Pillow; was not uninstalled
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-di61k1yp/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ghyb0uf_-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-di61k1yp/Pillow
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 309, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-di61k1yp/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ghyb0uf_-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-di61k1yp/Pillow

```

**Comment by jbarlow83** [comment]
I've run into your pip.log error before. It occurs when Pillow (Python
imaging) can't find libjpeg.

Probably you need:

sudo apt-get install libjpeg-dev

And then:

sudo pip uninstall Pillow
sudo pip install Pillo

Cheers.

**Comment by femifrak** [comment]
hmm, I installed lijpeg-dev and uninstalled Pillow, but installing Pillow with pip ended up in an error. :(
I installed python-pil with apt-get instead and this helped.
Do you intend to make ocrmypdf available with apt-get as well? (Please don't throw a pillow at me now.)

**Comment by jbarlow83** [comment]
Sorry about that, yes, on Ubuntu (I think you said you were on Ubuntu) you
usually want to install Python packages through apt-get if they are
available.

Someone volunteered to work on a Debian package apt-get and it will be
available from Debian sid soon. Which is great, because packaging things
for Debian sounds terrifying to me. It might be a while before the package
propagates to Ubuntu, although there's a way to set up custom package
authorities or something.
