### ISSUE TITLE
Traceback (most recent call last):   File "watcher.py", line 25, in <module>     import pikepdf ModuleNotFoundError: No module named 'pikepdf'

### ISSUE THREAD

**Issue by pedrohcmds** [jbarlow83/OCRmyPDF#516]
**Describe the issue**
Can`t use watcher.py to monitorate a certain dir. When i try to excecute
 `python3 watcher.py` 
the following error happens

`Traceback` (most recent call last):
  File "watcher.py", line 25, in <module>
    import pikepdf
ModuleNotFoundError: No module named `'pikepdf'`

How to fix ?

**Comment by pedrohcmds** [comment]
I've advanced in the problem by uninstalling de apt OcrMyPDF program for linux and re-installing in Python. Still, when I do try to excecute 
`python3 watcher.py`
The following error message: '
