### ISSUE TITLE
Conversion fails if tesseract-pagesegmode is 2

### ISSUE THREAD

**Issue by rahular** [jbarlow83/OCRmyPDF#549]
**Describe the bug**
I am trying to convert a 2 column pdf with the following command:

`ocrmypdf -l eng+san 1.pdf 1.out.pdf --sidecar 1.txt`

It works pretty well, but gets confused due to the additional column and combines text from both columns together. So I try:

`ocrmypdf -l eng+san 1.pdf 1.out.pdf --tesseract-pagesegmode 2 --sidecar 1.txt`

and it fails saying that it could not find some temporary file. Here is stack trace when I run in verbose mode:

```
└─$ ocrmypdf -l eng+san 1.pdf 1.out.pdf  --tesseract-pagesegmode 2 --sidecar 1.txt -v1
  DEBUG - ocrmypdf 9.7.2
  DEBUG - Running: ['tesseract', '--list-langs']
  DEBUG - Running: ['gs', '--version']
  DEBUG - Running: ['tesseract', '-l', 'san+eng', '--print-parameters', 'pdf']
  DEBUG - Running: ['tesseract', '--version']
  DEBUG - Running: ['tesseract', '--version']
  DEBUG - Found tesseract 4.1.1
  DEBUG - Found gs 9.27
  DEBUG - Found qpdf 10.0.1
  DEBUG - os.symlink(13F_Chapter_1_1.pdf, /var/folders/mh/jp3jl3vs08x1xv8_dpvjw7l4k26rf6/T/com.github.ocrmypdf.3zrqf705/origin)
  DEBUG - os.symlink(/var/folders/mh/jp3jl3vs08x1xv8_dpvjw7l4k26rf6/T/com.github.ocrmypdf.3zrqf705/origin, /var/folders/mh/jp3jl3vs08x1xv8_dpvjw7l4k26rf6/T/com.github.ocrmypdf.3zrqf705/origin.pdf)
  DEBUG - Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=txtwrite', '-dTextFormat=0', '-o', '-', '/var/folders/mh/jp3jl3vs08x1xv8_dpvjw7l4k26rf6/T/com.github.ocrmypdf.3zrqf705/origin.pdf', '-sstdout=%stderr']
Scan: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1049.52page/s]
   INFO - Start processing 5 pages concurrently
  DEBUG - Rotations for page 0: [text, auto, misalign, content] = 0, 0, 0, 0                                                                
  DEBUG - Rotations for page 3: [text, auto, misalign, content] = 0, 0, 0, 0                                                                
  DEBUG - Rotations for page 2: [text, auto, misalign, content] = 0, 0, 0, 0                                                                
  DEBUG - Rotations for page 4: [text, auto, misalign, content] = 0, 0, 0, 0                                                                
  DEBUG - Rotations for page 1: [text, auto, misalign, content] = 0, 0, 0, 0                                                                
OCR: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 5.0/5.0 [00:02<00:00,  2.26page/s]
  ERROR - An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/9.7.2_1/libexec/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 396, in run_pipeline
    exec_concurrent(context)
  File "/usr/local/Cellar/ocrmypdf/9.7.2_1/libexec/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 316, in exec_concurrent
    text = merge_sidecars(sidecars, context)
  File "/usr/local/Cellar/ocrmypdf/9.7.2_1/libexec/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 805, in merge_sidecars
    with open(txt_file, 'r', encoding="utf-8") as in_:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/mh/jp3jl3vs08x1xv8_dpvjw7l4k26rf6/T/com.github.ocrmypdf.3zrqf705/000001_ocr_tess.txt'
```

[Here](https://drive.google.com/open?id=1Zx2Qb0uprxXKM2qOjcljd5S-Cdftoavc) is the file I am trying to convert.

**System**
 - OS: macOS
 - OCRmyPDF Version: `9.7.2`
 - How did you install ocrmypdf? `brew install ocrmypdf`

**Comment by jbarlow83** [comment]
`--tesseract-pagesegmode 2` means "Automatic page segmentation, but no OSD, or OCR. "

If OCR is turned off, no OCR data is generated, then yes, an error occurs when we try to find the OCR data.

You probably want `pagesegmode 3` but I think that's the default. I don't believe there is any command to tell Tesseract you have a two column page, despite this being such a common situation.

**Comment by rahular** [comment]
Oops, yes that makes sense. Closing this.
