### ISSUE TITLE
Synology - Docker - Watcher.py - OCRmyPDF doesn't wait while file is being created

### ISSUE THREAD

**Issue by nasi-be** [jbarlow83/OCRmyPDF#552]
I'm running OCRmyPDF Docker-Container with entrypoint watcher.py on a Synology NAS but no OCR on an PDF is done.
I'm scanning a document from an MFP to a folder on the NAS. watcher.py is watching the folder and behaves differently with different parameters:

My docker-compose-file looks like this:
```
  ocrmypdf:
    image: jbarlow83/ocrmypdf
    container_name: ocrmypdf
    volumes:
      - "/volume1/homes/xxx/xxx/ScanInput:/input"
      - "/volume1/homes/xxx/xxx/Output:/output"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/TZ:/etc/timezone:ro"
    environment:
      - "OCR_INPUT_DIRECTORY=/input"
      - "OCR_OUTPUT_DIRECTORY=/output"
      - "OCR_POLL_NEW_FILE_SECONDS=5"
      - "OCR_USE_POLLING=True"
      - "OCR_ON_SUCCESS_DELETE=0"
      - "OCR_OUTPUT_DIRECTORY_YEAR_MONT=0"
      - "OCR_DESKEW=1"
      - "OCR_LOGLEVEL=DEBUG"
      - "PYTHONUNBUFFERED=0"
    entrypoint: python3
    command: watcher.py
    restart: always
```
I tested with the parameters OCR_USE_POLLING=True/<unset> and OCR_POLL_NEW_FILE_SECONDS=5/<unset>
(<unset> mean, that the Parameter was not set in the docker-compose file)

I did 4 tests with every combination of this 2 parameters.
When not setting OCR_POLL_NEW_FILE_SECONDS, I get this Log-output:
(One time with USE_POLLING=True und after this with USE_POLLING=False)
Watcher.py tries 5 times to access the document, while it is not ready. The scanner is not so fast, so it is possible, that the document is not ready.

```
   INFO - Starting OCRmyPDF watcher with config:
Input Directory: /input
Output Directory: /output
Output Directory Year & Month: False
ON_SUCCESS_DELETE: True
DESKEW: True
ARGS: {}
POLL_NEW_FILE_SECONDS: 1
USE_POLLING: False
LOGLEVEL: DEBUG
   INFO - --------------------
   INFO - New file: /input/est20200503_113509.pdf. Waiting until fully loaded...
   INFO - Before open
   INFO - File /input/est20200503_113509.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
   INFO - Before open
   INFO - File /input/est20200503_113509.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_113509.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Before open
   INFO - File /input/est20200503_113509.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_113509.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Before open
   INFO - File /input/est20200503_113509.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_113509.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Before open
   INFO - File /input/est20200503_113509.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_113509.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Gave up waiting for /input/est20200503_113509.pdf to become ready
```

```
   INFO - Starting OCRmyPDF watcher with config:
Input Directory: /input
Output Directory: /output
Output Directory Year & Month: False
ON_SUCCESS_DELETE: True
DESKEW: True
ARGS: {}
POLL_NEW_FILE_SECONDS: 1
USE_POLLING: True
LOGLEVEL: DEBUG
   INFO - --------------------
   INFO - New file: /input/est20200503_114248.pdf. Waiting until fully loaded...
   INFO - Before open
   INFO - File /input/est20200503_114248.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_114248.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Before open
   INFO - File /input/est20200503_114248.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
   INFO - Before open
   INFO - File /input/est20200503_114248.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_114248.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Before open
   INFO - File /input/est20200503_114248.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_114248.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Before open
   INFO - File /input/est20200503_114248.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_114248.pdf: unable to find trailer dictionary while recovering damaged file
   INFO - Gave up waiting for /input/est20200503_114248.pdf to become ready
```

So I tried to set OCR_POLL_NEW_FILE_SECONDS=5 (25 Seconds within 5 tries with a delay of 5 seconds is more than enough for a 1-page document) and expected the document to be handled by ocrmypdf, but the following messages are logged:
(Again one time with USE_POLLING=True und after this with USE_POLLING=False)

```
   INFO - Starting OCRmyPDF watcher with config:
Input Directory: /input
Output Directory: /output
Output Directory Year & Month: False
ON_SUCCESS_DELETE: True
DESKEW: True
ARGS: {}
POLL_NEW_FILE_SECONDS: 5
USE_POLLING: True
LOGLEVEL: DEBUG
   INFO - --------------------
   INFO - New file: /input/est20200503_114930.pdf. Waiting until fully loaded...
   INFO - Before open
   INFO - File /input/est20200503_114930.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_114930.pdf: unable to find trailer dictionary while recovering damaged file
```
```
   INFO - Starting OCRmyPDF watcher with config:
Input Directory: /input
Output Directory: /output
Output Directory Year & Month: False
ON_SUCCESS_DELETE: True
DESKEW: True
ARGS: {}
POLL_NEW_FILE_SECONDS: 5
USE_POLLING: False
LOGLEVEL: DEBUG
   INFO - --------------------
   INFO - New file: /input/est20200503_112500.pdf. Waiting until fully loaded...
   INFO - Before open
   INFO - File /input/est20200503_112500.pdf is not ready yet
   INFO - Exception was
Traceback (most recent call last):
  File "watcher.py", line 72, in wait_for_file_ready
    pdf = pikepdf.open(file_path)
  File "/usr/local/lib/python3.7/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /input/est20200503_112500.pdf: unable to find trailer dictionary while recovering damaged file
```

Watcher.py neither gives a positive ("Attempting to OCRmyPDF...") nor a negative ("Giving up...") message. But when scanning a second document the same messages appear, so I think the proccess isn't stuck.

Any ideas?

**Comment by jbarlow83** [comment]
There is no solution to the problem of a file being held open and written to very slowly from an external device. Some sloppy software will open and then close files multiple times, editing them in place and such. You should arrange for finished files to be copied to the watched folder when done, or set the threshold high enough to allow files to actually finished.

File watching is always flaky over networks. This includes Docker container to host communications. Ideally, the watcher should run on the "server", i.e. the system with the physical storage hardware. Client side watching is never going to work well.

**Comment by nasi-be** [comment]
Hi,

thanks for the reply.

> ... or set the threshold high enough to allow files to actually finished

I tried to do this, but it looks like, when setting OCR_POLL_NEW_FILE_SECONDS the script doesn't wait 5 times the entered seconds. (Like you can see in the logs)

But when there is no solution I have to try the synology-script or something else and only start ocrmypdf in the docker script (without using watcher.py).

**Comment by jbarlow83** [comment]
I can't reproduce this behavior, but it sounds like you have modified the script (e.g. the message "Before open") does not appear in the original. Closing due to not reproduced and inactivity.
