### ISSUE TITLE
pdfminer version issue again

### ISSUE THREAD

**Issue by chrisberkhout** [jbarlow83/OCRmyPDF#566]
**Describe the bug**

Dependency version conflict similar to https://github.com/jbarlow83/OCRmyPDF/issues/457

Error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pdfminer.six 20200517 (/usr/lib/python3.8/site-packages), Requirement.parse('pdfminer.six<=20200402,>=20181108'), {'ocrmypdf'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3262, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pdfminer.six<=20200402,>=20181108' distribution was not found and is required by ocrmypdf
```

**To Reproduce**

```bash
ocrmypdf
```

**Expected behavior**

Should work with the latest stable `pdfminer` (20200517).

**System**

 - OS: Arch Linux 5.6.14.arch1-1
 - OCRmyPDF Version: 9.8.0-1
 - OCRmyPDF Installation: [Arch Linux AUR package](https://aur.archlinux.org/packages/ocrmypdf/)
 - pdfminer Version: 20200517

**Comment by chrisberkhout** [comment]
Fixed in 9.8.1
