### ISSUE TITLE
API ocrmypdf: argument language is ignored

### ISSUE THREAD

**Issue by alinshrr** [jbarlow83/OCRmyPDF#568]
**Describe the bug** **To Reproduce**
If I call `ocrmypdf.ocr(fPdf, fOutput, language="deu")` from python I get this error:
``` Output
Traceback (most recent call last):
  File "/data/projects/ocr/main.py", line 11, in <module>
    ocrmypdf.ocr(fPdf, fOutput, language="deu")
  File "/home/<user>/.local/share/virtualenvs/ocr-dBRsyPH2/lib/python3.8/site-packages/ocrmypdf/api.py", line 272, in ocr
    check_options(options)
  File "/home/<user>/.local/share/virtualenvs/ocr-dBRsyPH2/lib/python3.8/site-packages/ocrmypdf/_validation.py", line 305, in check_options
    check_options_languages(options)
  File "/home/<user>/.local/share/virtualenvs/ocr-dBRsyPH2/lib/python3.8/site-packages/ocrmypdf/_validation.py", line 82, in check_options_languages
    if not languages.issubset(tesseract.languages()):
  File "/home/<user>/.local/share/virtualenvs/ocr-dBRsyPH2/lib/python3.8/site-packages/ocrmypdf/exec/tesseract.py", line 127, in languages
    raise MissingDependencyError(lang_error(output))
ocrmypdf.exceptions.MissingDependencyError: Tesseract failed to report available languages.
Output from Tesseract:
-----------
Error opening data file /usr/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
List of available languages (2):
deu
osd
```
I think the problem is that the API calls tesseract with the argument `--language` instead of `-l`

**System**
 - OS: Archlinux
 - OCRmyPDF Version: 9.8.1
 - How did you install ocrmypdf? pip

**Comment by jbarlow83** [comment]
I think Tesseract or ocrmypdf requires the English language pack to be
installed even if it's not going to be used. Try installing eng.traineddata.

**Comment by alinshrr** [comment]
Thanks for the quick response. 
Tesseract and ocrmypdf work without English language pack (using `-l deu`). But I can confirm that the api call works as well after I installed eng.traineddata.

Thanks for your help!
