### ISSUE TITLE
No warning given when using "--clean" clause if unpaper is not installed

### ISSUE THREAD

**Issue by shatteringlass** [jbarlow83/OCRmyPDF#58]
`--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 328, in getMessage
    msg = str(self.msg)
  File "/usr/local/lib/python3.5/site-packages/ruffus/ruffus_exceptions.py", line 127, in __str__
    message += self.get_nth_exception_str (ii)
  File "/usr/local/lib/python3.5/site-packages/ruffus/ruffus_exceptions.py", line 116, in get_nth_exception_str
    task_name, job_name, exception_name, exception_value, exception_stack = self.args[nn]
ValueError: too many values to unpack (expected 5)
Call stack:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/managers.py", line 195, in handle_request
    result = func(c, *args, **kwds)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/managers.py", line 386, in accept_connection
    self.serve_client(c)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/managers.py", line 241, in serve_client
    res = function(*args, **kwds)
Message: RethrownJobError('ocrmypdf.main.preprocess_clean', "Job  = [.../com.github.ocrmypdf.l6ke91hk/000001.pp-deskew.png -> .../com.github.ocrmypdf.l6ke91hk/000001.pp-clean.png, <ocrmypdf.main.WrappedLogger>, [{'xres': Decimal('400'), 'pageno': 0, 'images': [{'color': 'icc', 'height': 4677, 'dpi_w': Decimal('400'), 'dpi_h': Decimal('400'), 'dpi': Decimal('400.000'), 'comp': '?', 'name': '/Im1', 'width': 3307, 'enc': 'jpeg', 'bpc': 8}], 'has_text': False, 'yres': Decimal('400'), 'height_inches': Decimal('11.6925'), 'height_pixels': 4677, 'width_pixels': 3307, 'width_inches': Decimal('8.2675')}], <unlocked _thread.lock>]", 'builtins.FileNotFoundError', "([Errno 2] No such file or directory: '/var/folders/3x/ns1_qnqj35q42353wws7h9p40000gn/T/tmp65ynoino.ppm')", 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/unpaper.py", line 73, in run\n    universal_newlines=True, stdout=PIPE, stderr=PIPE\n  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__\n    restore_signals, start_new_session)\n  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child\n    raise child_exception_type(errno_num, err_msg)\nFileNotFoundError: [Errno 2] No such file or directory: \'unpaper\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.5/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions\n    register_cleanup, touch_files_only)\n  File "/usr/local/lib/python3.5/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files\n    ret_val = user_defined_work_func(*params)\n  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/main.py", line 635, in preprocess_clean\n    unpaper.clean(input_file, output_file, dpi, log)\n  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/unpaper.py", line 101, in clean\n    \'--no-deskew\',        # don\'t deskew\n  File "/usr/local/lib/python3.5/site-packages/ocrmypdf/unpaper.py", line 79, in run\n    Image.open(output_pnm.name).save(output_file)\n  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tempfile.py", line 502, in __exit__\n    self.close()\n  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tempfile.py", line 509, in close\n    self._closer.close()\n  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tempfile.py", line 446, in close\n    unlink(self.name)\nFileNotFoundError: [Errno 2] No such file or directory: \'/var/folders/3x/ns1_qnqj35q42353wws7h9p40000gn/T/tmp65ynoino.ppm\'\n')
Arguments: ()
`

**Comment by jbarlow83** [comment]
What is the output of unpaper --version ?

**Comment by shatteringlass** [comment]
Mh, unpaper does not seem to be installed (*unknown command*, that is)

**Comment by jbarlow83** [comment]
Fix pushed
