### ISSUE TITLE
OCRmyPDF fails to work with reportlab=3.5

### ISSUE THREAD

**Issue by AndreasAZiegler** [jbarlow83/OCRmyPDF#593]
**Describe the bug**
OCRmyPDF fails to start due to a missing dependency

**To Reproduce**
Just starting OCRmyPDF

```bash
ocrmypdf
```

**Expected behavior**
OCRmyPDF shows me its option

**Error**
```bash
Traceback (most recent call last):
  File "/home/andreasziegler/miniconda3/bin/ocrmypdf", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/andreasziegler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3253, in <module>
    @_call_aside
  File "/home/andreasziegler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/home/andreasziegler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/andreasziegler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/andreasziegler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/andreasziegler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'reportlab>=3.3.0' distribution was not found and is required by ocrmypdf
```
But I have ``community/python-reportlab 3.5.42-3`` installed

**System**
 - OS: (Arch) Linux
 - OCRmyPDF Version: 10.2.0
 - How did you install ocrmypdf?
```bash
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/ocrmypdf.tar.gz
tar xvzf ocrmypdf.tar.gz
cd ocrmypdf
makepkg -sri
```

**Comment by jbarlow83** [comment]
I believe this is an issue with the ArchLinux package and/or miniconda. Please report the issue to AUR.

**Comment by sproid-i** [comment]
On a thread I made on Manjaro forum someone [share](https://forum.manjaro.org/t/ocrmypdf-broken-again/155648/7?u=sproid) a fix for that as:
`pip install --upgrade --force-reinstall reportlab`
