### ISSUE TITLE
cannot start ocrmypdf after update

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#602]
**Describe the issue**
After updating to the last version, starting the software gives error message.

**To Reproduce**
update from ver. 9 to 10.3.1 following the guidlines

```bash
/home/pim/.local/bin/ocrmypdf
```
**system output**
Traceback (most recent call last):
  File "/home/pim/.local/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.\_\_main__ import run
  File "/home/pim/.local/lib/python3.7/site-packages/ocrmypdf/\_\_init__.py", line 21, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/home/pim/.local/lib/python3.7/site-packages/ocrmypdf/pdfinfo/\_\_init__.py", line 19, in <module>
    from ocrmypdf.pdfinfo.info import Colorspace, Encoding, PdfInfo
  File "/home/pim/.local/lib/python3.7/site-packages/ocrmypdf/pdfinfo/info.py", line 37, in <module>
    from ocrmypdf.pdfinfo.layout import get_page_analysis, get_text_boxes
  File "/home/pim/.local/lib/python3.7/site-packages/ocrmypdf/pdfinfo/layout.py", line 29, in <module>
    from pdfminer.pdfdocument import PDFTextExtractionNotAllowed
ImportError: cannot import name 'PDFTextExtractionNotAllowed' from 'pdfminer.pdfdocument' (/home/pim/.local/lib/python3.7/site-packages/pdfminer/pdfdocument.py)

**System:**
- OS:xubuntu 18.04
- OCRmyPDF Version: 10.3.1

**Additional context**
there was no error message during installation. (Requirement already satisfied, after second try)
```bash
> pip --version
```
pip 20.1.1 from /home/pim/.local/lib/python3.6/site-packages/pip (python 3.6)

Please advice me, thanks

**Comment by pigmonkey** [comment]
This is due to a breaking change in version 20200720 of python-pdfminer.six. The change has been reversed, but the fixed version of python-pdfminer.six has not been officially tagged yet.

Further details can be seen [on the OCRMyPDF AUR page](https://aur.archlinux.org/packages/ocrmypdf/#comment-758604).

**Comment by femifrak** [comment]
Thanks for the really fast reply!!

I mananged to downgrade
```bash
pip3 uninstall  pdfminer.six
pip3 install --user pdfminer.six==20200517
```
and/or
```bash
pip3 uninstall pdfminer
pip3 install --user pdfminer==20191103
```
But still could not start ocrmypdf.
I think I'd better wait a few days (?)

**Comment by jbarlow83** [comment]
You could try installing it to a virtual machine for now.

**Comment by femifrak** [comment]
- Why do you think a vm would help? Do you mean a vm with a different operating system? Which one does not show this problem?

- I know it's not exactly predictable, but what approximate time frame do we have to assume for an update of pdfminer?

- Would a downgrade of ocrmypdf help? And which version would be the latest one which is working?

**Comment by jbarlow83** [comment]
I mean Python virtual environment, sorry. I think the fixed pdfminer is out now.

**Comment by femifrak** [comment]
perfect 10.3.1 works again :)
thanks!

**Comment by balki** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 33, in <module>
    sys.exit(load_entry_point('ocrmypdf==10.3.2', 'console_scripts', 'ocrmypdf')())
  File "/usr/bin/ocrmypdf", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/ocrmypdf/__init__.py", line 21, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/__init__.py", line 19, in <module>
    from ocrmypdf.pdfinfo.info import Colorspace, Encoding, PdfInfo
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 37, in <module>
    from ocrmypdf.pdfinfo.layout import get_page_analysis, get_text_boxes
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/layout.py", line 29, in <module>
    from pdfminer.pdfdocument import PDFTextExtractionNotAllowed
ImportError: cannot import name 'PDFTextExtractionNotAllowed' from 'pdfminer.pdfdocument' (/usr/lib/python3.8/site-packages/pdfminer/pdfdocument.py)

```

Still not working for me.
