### ISSUE TITLE
Multiple Page PDF Error (KeyError: '/Pages')

### ISSUE THREAD

**Issue by tbirdss** [jbarlow83/OCRmyPDF#638]
**Describe the bug**
While running with Multipage pdf show error

```
  ERROR - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pipeline.py", line 222, in repair_and_parse_pdf
    pdfinfo = PdfInfo(output_file)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 725, in __init__
    self._pages = _pdf_get_all_pageinfo(infile)
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo.py", line 642, in _pdf_get_all_pageinfo
    return [PageInfo(pdf, n, infile) for n in range(pdf.numPages)]
  File "/usr/lib/python3/dist-packages/PyPDF2/pdf.py", line 1158, in <lambda>
    numPages = property(lambda self: self.getNumPages(), None, None)
  File "/usr/lib/python3/dist-packages/PyPDF2/pdf.py", line 1155, in getNumPages
    self._flatten()
  File "/usr/lib/python3/dist-packages/PyPDF2/pdf.py", line 1506, in _flatten
    pages = catalog["/Pages"].getObject()
  File "/usr/lib/python3/dist-packages/PyPDF2/generic.py", line 520, in __getitem__
    return dict.__getitem__(self, key).getObject()
KeyError: '/Pages'

```

**System**
 - OS: [Linux]
 - OCRmyPDF Version: ``ocrmypdf  6.1.2``
 - How did you install ocrmypdf?  apt-get install ocrmypdf

**Comment by jbarlow83** [comment]
This version is quite old. Please see the documentation for steps to
upgrade.
