### ISSUE TITLE
linuxbrew install of 11.2.1 is failing due to reportlab 3.5.53 maybe due to xorg (vs. linuxbrew/xorg?)

### ISSUE THREAD

**Issue by mdsteveb** [jbarlow83/OCRmyPDF#653]
**Describe the bug**
Attempting to upgrade ocrmypdf on linux with linuxbrew hasn't worked for me since 11.0.2. The upgrade fails during build while attempting to install the resource reportlab 3.5.53.

**To Reproduce**
On my Ubuntu 18.04 system:
```
$ brew upgrade --debug ocrmypdf
....everything seems okay up to here...
tar xof /home/xxxxxxx/.cache/Homebrew/downloads/e742c8e119ae51552ef7a01513165d2461b47654e0811af1baa6190a51b68899--reportlab-3.5.53.tar.gz -C /tmp/d20201015-22581-11nx81f
cp -pR /tmp/d20201015-22581-11nx81f/reportlab-3.5.53/. /tmp/ocrmypdf--reportlab-20201015-22581-u3m8n2/reportlab-3.5.53
==> /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/bin/pip install -v
Last 15 lines from /home/xxxxxxx/.cache/Homebrew/Logs/ocrmypdf/19.pip:
    installed = install_given_reqs(
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 273, in runner
    call_subprocess(
  File "/home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ut_jhjk6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ut_jhjk6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rxpggig3/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/include/site/python3.8/reportlab Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-mmnzlvw_'
/usr/bin/curl --version
java -version
/usr/bin/ruby -e puts\ RUBY_VERSION
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:17:in 'raise'
FormulaUnavailableError: No available formula with the name "xorg" 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:17:in 'raise'
BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/ocrmypdf/11.2.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/ocrmypdf--reportlab-20201015-22581-u3m8n2/reportlab-3.5.53
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/ocrmypdf-20201015-22581-dal0u5
```

**Expected behavior**
Successful build/install.

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: brew's python@3.8 (dependency in formula)
 - OCRmyPDF version: current formula is 11.2.1

**Additional context**
Apologies if I'm not tracing the source of the error properly. Let me know if you need more info.

I'm not sure what's going on with the `xorg` vs `linuxbrew/xorg/...` stuff. I get a ton of warnings about it when I do brew updates, but I'm not sure what the correct resolution is. This is the first formula I've run into that seems to actually break because of it. It looks like most but not all of the X-related brew packages I have installed are of the linuxbrew/xorg/ type. However it is true that `brew search xorg` does not return any actual formulae named `xorg` .

**Comment by jbarlow83** [comment]
I didn't even know Linuxbrew worked. I think you'll have to take this up with the Linuxbrew maintainers. I'm afraid I can't help because I don't know anything about what's going on.
