### ISSUE TITLE
Ocrmypdf Distribution Not Found

### ISSUE THREAD

**Issue by gabemorris12** [jbarlow83/OCRmyPDF#659]
**Describe the bug**
Pyinstaller was used to successfully create an executable file, but upon running the .exe, it crashes. 

**To Reproduce**
To reproduce the error, make sure you flag --consoled when running the pyinstaller command. Then run the executable from the command prompt. Then it will raise pkg_resources.DistributionNotFound error.

**Expected behavior**
I expected all dependencies to be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/73252281/96768967-16062d80-13a4-11eb-9fdc-d1f5225fd857.png)

**System (please complete the following information):**
 - OS: windows 10
 - Python version: 3.8.3
 - OCRmyPDF version: 10.3.3

**Additional context**
The .py script runs perfectly fine. There's just a problem with pyinstaller not finding the distribution.

**Comment by jbarlow83** [comment]
I think you'll have to ask for support from the PyInstaller people, since I don't know much about it.

ocrmypdf's use of cffi to access a C library, and its use of third party executables like Tesseract and Ghostscript, may be problematic for packaging. 

If you can identify a specific issue with ocrmypdf that is an obstacle to generating this installer, please open a PR.

**Comment by gabemorris12** [comment]
@jbarlow83 I it to run! I should have gone to pyinstaller first, so sorry about that. The fix can be found here: https://github.com/pyinstaller/pyinstaller/issues/4809

I had to create hook files for both ocrmypdf module and the pikepdf module by using the --additional-hooks-dir _HooksFolderPath_ flag. Thanks for the quick response.

**Comment by jbarlow83** [comment]
Would you mind sharing your full instructions? Maybe I'll be able to automate it one day.

**Comment by gabemorris12** [comment]
@jbarlow83 
You have to make two different .py scripts in a folder within your project. For my example, I made a folder called Hooks, and these are the two scripts that I made:
**hook-ocrmypdf.py**
`
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = collect_all('ocrmypdf')
`
Having this hook alone will allow the app to run; however, it is not enough. In your program, once it attempts to execute the ocrmypdf.ocr() function, it will raise another error. I cannot remember what error it was exactly, but it was an error relating to a missing dependency within pikepdf. So the other script that you have to make is this: 
**hook-pikepdf.py**
`
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = collect_all('pikepdf')
`

Now when you package the main script with pyinstaller, you must include this flag: --additional-hooks-dir _HooksFolderPath_.

**Comment by woaidianqian** [comment]
pyinstaller pdf识别.py --additional-hooks-dir HooksFolderPath
![image](https://user-images.githubusercontent.com/10897660/119807441-b8c3f300-bf15-11eb-9175-b0c38f1ae7ab.png)
it works！

**Comment by koolkunz** [comment]
Getting this error after following the instructions above:

Traceback (most recent call last):
  File "pyi_rth_pyoc.py", line 30, in <module>
  File "ocrmypdf\api.py", line 324, in ocr
    plugin_manager = get_plugin_manager(plugins)
  File "ocrmypdf\_plugin_manager.py", line 104, in get_plugin_manager
    return OcrmypdfPluginManager(
  File "ocrmypdf\_plugin_manager.py", line 45, in __init__
    self.setup_plugins()
  File "ocrmypdf\_plugin_manager.py", line 69, in setup_plugins
    for module in sorted(
TypeError: '<' not supported between instances of 'FrozenImporter' and 'FileFinder'

can anyone help?

**Comment by jbarlow83** [comment]
@koolkunz Look up how to use pyinstaller with a project that uses pluggy as a plugin manager. pytest is an example of such a project. You may also need add ocrmypdf/builtin_plugins to the list of dynamic plugins that will be used - ocrmypdf installs some of its own plugins by default so that others can override them.

**Comment by koolkunz** [comment]
> @koolkunz Look up how to use pyinstaller with a project that uses pluggy as a plugin manager. pytest is an example of such a project. You may also need add ocrmypdf/builtin_plugins to the list of dynamic plugins that will be used - ocrmypdf installs some of its own plugins by default so that others can override them.

`pyinstaller --copy-metadata pikepdf --copy-metadata ocrmypdf --collect-submodules ocrmypdf --collect-datas ocrmypdf.data sample.py`

This is all I had to do to get it working^.

But now I have another small issue, that is if I am running my GUI application in no console mode, ocrmypdf keeps opening multiple console windows of tesseract (I think equal to the number of jobs being processed) and ghostscript executables with no output.

I already have logging set to -1:
`configure_logging(verbosity=-1, progress_bar_friendly=False)`

Is there any other way to suppress these console windows from showing up at all?

**Comment by insinfo** [comment]
@koolkunz
could you make this available on google drive so i can download and use it on my windows notebook? I was in need of making some PDF Searchable. In my notebook I already have the latest version of tesseract v5.3.0, ghostscript 10.01.1 and python 3.10.8

**Comment by koolkunz** [comment]
> @koolkunz could you make this available on google drive so i can download and use it on my windows notebook? I was in need of making some PDF Searchable. In my notebook I already have the latest version of tesseract v5.3.0, ghostscript 10.01.1 and python 3.10.8

I'm still working on it and unless you want to distribute the exe you can just use ocrmypdf through simple python code or even just directly in the command line.

**Comment by zeekias** [comment]
I have the same problem, someone could help me?

**Comment by zeekias** [comment]
How can i disable the tesseract prompt?

**Comment by lugi777** [comment]
@koolkunz Have you found a way to prevent the console windows showing up?

**Comment by koolkunz** [comment]
> @koolkunz Have you found a way to prevent the console windows showing up?

Unfortunately no, ultimately I just went with the console window option while building the exe using pynistaller

**Comment by Brisk4t** [comment]
> > [@koolkunz](https://github.com/koolkunz) Look up how to use pyinstaller with a project that uses pluggy as a plugin manager. pytest is an example of such a project. You may also need add ocrmypdf/builtin_plugins to the list of dynamic plugins that will be used - ocrmypdf installs some of its own plugins by default so that others can override them.
> 
> `pyinstaller --copy-metadata pikepdf --copy-metadata ocrmypdf --collect-submodules ocrmypdf --collect-datas ocrmypdf.data sample.py`
> 
> This is all I had to do to get it working^.
> 
> But now I have another small issue, that is if I am running my GUI application in no console mode, ocrmypdf keeps opening multiple console windows of tesseract (I think equal to the number of jobs being processed) and ghostscript executables with no output.
> 
> I already have logging set to -1: `configure_logging(verbosity=-1, progress_bar_friendly=False)`
> 
> Is there any other way to suppress these console windows from showing up at all?
> 
> edit: Added Screenshot ![Screenshot (203)](https://user-images.githubusercontent.com/6692008/233638427-8d11598f-7f53-40b8-8462-c60738676cb3.png)

If anyone does stumble into this extremely niche issue, a hotfix you can use is to monkey patch the subprocess.Popen() function that OCRmyPDF and its submodules (Tesseract and GhostScript) use to prevent them from opening new windows. 

```
# Patch OCRmyPDF to suppress all consoles
if platform.system() == "Windows":
    # Patch subprocess to prevent window popup on Windows
    class NoWindowPopen(subprocess.Popen):
        def __init__(self, *args, **kwargs):
            kwargs['creationflags'] = kwargs.get('creationflags', 0) | subprocess.CREATE_NO_WINDOW
            super().__init__(*args, **kwargs)

    subprocess.Popen = NoWindowPopen

import ocrmypdf
```

Note that its important that this block runs **before importing ocrmypdf** 

A more robust solution would be to add a flag to the .ocr function call that then passes on the flag to .Popen()
