### ISSUE TITLE
--redo-ocr is failing with certain files

### ISSUE THREAD

**Issue by ah3243** [jbarlow83/OCRmyPDF#692]
**Describe the bug**
Certain files(specifically academic papers) keep failing when i try and redo instead of force the ocr. I get a large amount of output to the terminal then at the end it freezes on the final 'scanning contents' progress bar. The documents work fine with --force-ocr and --redo-ocr works on other non-academic papers. 

**To Reproduce**
```bash
ocrmypdf --redo-ocr input.pdf output.pdf
```

** The last few lines of the terminal output **
```
Message: 'add_results: %r'
Arguments: (((28311, /'F6'),),)
Page: {'CropBox': [0, 0, 612, 792], 'Parent': <PDFObjRef:204>, 'Contents': [<PDFObjRef:221>, <PDFObjRef:222>, <PDFObjRef:235>, <PDFObjRef:246>, <PDFObjRef:252>, <PDFObjRef:253>, <PDFObjRef:256>, <PDFObjRef:257>], 'Rotate': 0, 'MediaBox': [0, 0, 612, 792], 'Thumb': <PDFObjRef:186>, 'Resources': <PDFObjRef:211>, 'Type': /'Page'}
Scanning contents:  93%|████████████████████████████████████████████████████████████████████████████▌     | 14/15 [01:01<00:02,  2.88s/page]--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 1431, in emit
    self.enqueue(self.prepare(record))
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 1393, in enqueue
    self.queue.put_nowait(record)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 138, in put_nowait
    return self.put(obj, False)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 90, in put
    raise Full
queue.Full
Call stack:
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 642, in _pdf_pageinfo_sync
    page = PageInfo(worker_pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 695, in __init__
    self._pageinfo = _pdf_get_pageinfo(
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 575, in _pdf_get_pageinfo
    miner = get_page_analysis(infile, pageno, pscript5_mode)
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/ocrmypdf/pdfinfo/layout.py", line 239, in get_page_analysis
    interp.process_page(next(page))
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 908, in render_contents
    self.execute(list_value(streams))
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 919, in execute
    (_, obj) = parser.nextobject()
  File "/usr/local/Cellar/ocrmypdf/11.3.4/libexec/lib/python3.9/site-packages/pdfminer/psparser.py", line 622, in nextobject
    log.debug('nextobject: %r', obj)
Message: 'nextobject: %r'
Arguments: ((28592, 0),)
Page: {'CropBox': [0, 0, 612, 792], 'Parent': <PDFObjRef:204>, 'Contents': <PDFObjRef:3>, 'Rotate': 0, 'MediaBox': [0, 0, 612, 792], 'Thumb': <PDFObjRef:187>, 'Resources': <PDFObjRef:2>, 'Type': /'Page'}
Scanning contents: 100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [01:01<00:00,  2.58s/page]
```

**Example file**
https://github.com/ah3243/MiscFiles/blob/main/ExamplePDF.pdf

**System**
 - OS: macOS
 - OCRmyPDF Version: 11.3.4
 - installed through homebrew version 2.6.1

**Comment by jbarlow83** [comment]
For whatever reason pdfminer.six floods the log message queue on this particular file.

**Comment by ah3243** [comment]
> For whatever reason pdfminer.six floods the log message queue on this particular file.

Ok this is happening with quite a lot of academic papers that I'm downloading, is there anyway to address this or allow it to complete the conversion? (I'm not worried about the terminal being flooded just that the conversion stalls.

**Comment by jbarlow83** [comment]
v11.4.0 fixes the issue.

Technical details: Since an internal message queue gets flooded, an internal message from a worker that all work is complete never gets through, so the supervisor waits indefinitely for this message. That's what you're seeing.

**Comment by ah3243** [comment]
Ok installed it through pip works perfectly thanks!
