### ISSUE TITLE
Build from source tarball

### ISSUE THREAD

**Issue by epa** [jbarlow83/OCRmyPDF#70]
Hi, I am trying to build on Fedora 23 using the source tarball <https://github.com/jbarlow83/OCRmyPDF/archive/v4.0.5.tar.gz>.  When I do so, as `pip3 install .`, I get the error below.  Am I starting with the correct source tree or as the message suggests do I need to get a different tarball?

````
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/eda/inst/OCRmyPDF-4.0.5
    Complete output from command python setup.py egg_info:

    Installed /tmp/easy_install-89ns07hv/pytest-runner-2.7.1/.eggs/setuptools_scm-1.11.0-py3.4.egg
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-2d81cgj_-build/.eggs/pytest_runner-2.7.1-py3.4.egg
    Searching for cffi>=1.5.0
    Reading https://pypi.python.org/simple/cffi/
    Best match: cffi 1.6.0
    Downloading https://pypi.python.org/packages/b6/98/11feff87072e2e640fb8320712b781eccdef05d588618915236b32289d5a/cffi-1.6.0.tar.gz#md5=2fae9160991afefb20ff0fbde3b14faf
    Processing cffi-1.6.0.tar.gz
    Writing /tmp/easy_install-e69ewjp5/cffi-1.6.0/setup.cfg
    Running cffi-1.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-e69ewjp5/cffi-1.6.0/egg-dist-tmp-zxzeckch
    creating /tmp/pip-2d81cgj_-build/.eggs/cffi-1.6.0-py3.4-linux-x86_64.egg
    Extracting cffi-1.6.0-py3.4-linux-x86_64.egg to /tmp/pip-2d81cgj_-build/.eggs

    Installed /tmp/pip-2d81cgj_-build/.eggs/cffi-1.6.0-py3.4-linux-x86_64.egg
    Searching for setuptools-scm-git-archive
    Reading https://pypi.python.org/simple/setuptools_scm_git_archive/
    Best match: setuptools-scm-git-archive 1.0
    Downloading https://pypi.python.org/packages/18/00/754438f629dfff1ecdbb31c8c23effe8bcfdbf65dbaf1cbed58eab286d82/setuptools_scm_git_archive-1.0.tar.gz#md5=cb4ca99e97edea548117fe0d80cbd089
    Processing setuptools_scm_git_archive-1.0.tar.gz
    Writing /tmp/easy_install-3fx6q4yf/setuptools_scm_git_archive-1.0/setup.cfg
    Running setuptools_scm_git_archive-1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3fx6q4yf/setuptools_scm_git_archive-1.0/egg-dist-tmp-3qt8zjv_

    Installed /tmp/easy_install-3fx6q4yf/setuptools_scm_git_archive-1.0/.eggs/setuptools_scm-1.11.0-py3.4.egg
    zip_safe flag not set; analyzing archive contents...
    zip_safe flag not set; analyzing archive contents...
    Moving setuptools_scm_git_archive-1.0-py3.4.egg to /tmp/pip-2d81cgj_-build/.eggs
    Moving setuptools_scm_git_archive-0-py3.4.egg to /tmp/pip-2d81cgj_-build/.eggs

    Installed /tmp/pip-2d81cgj_-build/.eggs/setuptools_scm_git_archive-1.0-py3.4.egg

    Installed /tmp/pip-2d81cgj_-build/.eggs/setuptools_scm_git_archive-0-py3.4.egg
    Searching for setuptools-scm
    Reading https://pypi.python.org/simple/setuptools_scm/
    Best match: setuptools-scm 1.11.0
    Downloading https://pypi.python.org/packages/cd/5f/e3a038292358058d83d764a47d09114aa5a8003ed4529518f9e580f1a94f/setuptools_scm-1.11.0.tar.gz#md5=4c5c896ba52e134bbc3507bac6400087
    Processing setuptools_scm-1.11.0.tar.gz
    Writing /tmp/easy_install-otvexao1/setuptools_scm-1.11.0/setup.cfg
    Running setuptools_scm-1.11.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-otvexao1/setuptools_scm-1.11.0/egg-dist-tmp-53a93ri1
    Moving setuptools_scm-1.11.0-py3.4.egg to /tmp/pip-2d81cgj_-build/.eggs

    Installed /tmp/pip-2d81cgj_-build/.eggs/setuptools_scm-1.11.0-py3.4.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.14
    Downloading https://pypi.python.org/packages/6d/31/666614af3db0acf377876d48688c5d334b6e493b96d21aa7d332169bee50/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935
    Processing pycparser-2.14.tar.gz
    Writing /tmp/easy_install-a96046vg/pycparser-2.14/setup.cfg
    Running pycparser-2.14/setup.py -q bdist_egg --dist-dir /tmp/easy_install-a96046vg/pycparser-2.14/egg-dist-tmp-0fp__duw
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Moving pycparser-2.14-py3.4.egg to /tmp/pip-2d81cgj_-build/.eggs

    Installed /tmp/pip-2d81cgj_-build/.eggs/pycparser-2.14-py3.4.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-2d81cgj_-build/setup.py", line 235, in <module>
        zip_safe=False)
      File "/usr/lib64/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-2d81cgj_-build/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/integration.py", line 19, in version_keyword
      File "/tmp/pip-2d81cgj_-build/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/__init__.py", line 104, in get_version
      File "/tmp/pip-2d81cgj_-build/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/__init__.py", line 82, in _do_parse
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-2d81cgj_-build'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary\
 metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-2d81cgj_-build
````

**Comment by jbarlow83** [comment]
I suggest making a git clone of the repository instead.
