### ISSUE TITLE
signal.pthread_sigmask not working in Cygwin

### ISSUE THREAD

**Issue by jrast** [jbarlow83/OCRmyPDF#701]
**Describe the bug**

Running OCRmyPDF on any file gives the following error:
AttributeError: module 'signal' has no attribute 'pthread_sigmask'

**Example Call with Output:**
````bash
$ ocrmypdf --language deu --verbose 2 DCP-920CDW_000448.pdf DCP-920CDW_000448-OCR1.pdf
  DEBUG ocrmypdf - ocrmypdf 11.4.1
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = List of available languages (4):
deu
deu_frak
eng
osd

  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 4.1.1
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '-l', 'deu', '--print-parameters', 'pdf']
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 9.53.3
  DEBUG ocrmypdf.helpers - pikepdf mmap disabled
  DEBUG ocrmypdf.helpers - os.symlink(DCP-920CDW_000448.pdf, /tmp/ocrmypdf.io.s7i2b9tf/origin)
  DEBUG ocrmypdf.helpers - os.symlink(/tmp/ocrmypdf.io.s7i2b9tf/origin, /tmp/ocrmypdf.io.s7i2b9tf/origin.pdf)
Scanning contents:   0%|          | 0/1 [00:00<?, ?page/s]Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/usr/local/lib/python3.8/site-packages/ocrmypdf/_concurrent.py", line 76, in thread_init
    signal.pthread_sigmask(signal.SIG_BLOCK, {signal.SIGBUS})
AttributeError: module 'signal' has no attribute 'pthread_sigmask'
````
and after hitting <CTRL-C>:

````bash
Scanning contents:   0%|          | 0/1 [02:55<?, ?page/s]
  ERROR ocrmypdf._sync - KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 851, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 355, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/local/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 155, in get_pdfinfo
    return PdfInfo(
  File "/usr/local/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 818, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/usr/local/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 674, in _pdf_pageinfo_concurrent
    exec_progress_pool(
  File "/usr/local/lib/python3.8/site-packages/ocrmypdf/_concurrent.py", line 112, in exec_progress_pool
    result = results.next()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 856, in next
    self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```` 
**System (please complete the following information):**
 - OS: Windows 10, using Cygwin (as described in the docs)
 - Python version: 3.8.3
 - OCRmyPDF version: 11.4.1

**Additional context**
I already had to fix [this pikepdf issue](https://github.com/pikepdf/pikepdf/issues/103) during the setup of PDFmyOCR but I don't think that this is related.

**Comment by jrast** [comment]
If I modify the `thread_init` function like this, OCRmyPDF runs as expected:

````
def thread_init(_queue, user_init, _loglevel):
    # As a thread, block SIGBUS so the main thread deals with it...
    #if hasattr(signal, 'SIGBUS'):  # --> Commented to fix bug
    #    signal.pthread_sigmask(signal.SIG_BLOCK, {signal.SIGBUS})  # Commented to fix bug
    if user_init:
        user_init()
````

**Comment by jbarlow83** [comment]
Fixed for next release - thanks
