### ISSUE TITLE
Strange PDF causes OSError: cannot open profile from string

### ISSUE THREAD

**Issue by jovandeginste** [jbarlow83/OCRmyPDF#706]
**Describe the bug**

When running ocrmypdf on a set of PDF invoices from a single specific contact, I get a stack trace. I would very well accept the response to be "sadly, there is nothing we can do here"; I still wanted to report this.

```text
ocrmypdf 11.3.3
Running: ['tesseract', '--list-langs']
No language specified; assuming --language eng
Running: ['tesseract', '--version']
Found tesseract 4.1.1
Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
Running: ['gs', '--version']
Found gs 9.53.3
pikepdf mmap disabled
os.symlink(2016-01.pdf, /tmp/com.github.ocrmypdf.x4e510be/origin)
os.symlink(/tmp/com.github.ocrmypdf.x4e510be/origin, /tmp/com.github.ocrmypdf.x4e510be/origin.pdf)
pikepdf mmap disabled                                                                                        
Scanning contents:   0%|                                                             | 0/1 [00:00<?, ?page/s]
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 360, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 154, in get_pdfinfo
    return PdfInfo(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 812, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 670, in _pdf_pageinfo_concurrent
    exec_progress_pool(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 112, in exec_progress_pool
    result = results.next()
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 641, in _pdf_pageinfo_sync
    page = PageInfo(worker_pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 694, in __init__
    self._pageinfo = _pdf_get_pageinfo(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 601, in _pdf_get_pageinfo
    for ci in _process_content_streams(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 511, in _process_content_streams
    yield from _find_regular_images(container, contentsinfo)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 431, in _find_regular_images
    yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 310, in __init__
    pim_icc = pim.icc
  File "/usr/lib64/python3.9/site-packages/pikepdf/models/image.py", line 387, in icc
    self._icc = ImageCms.ImageCmsProfile(iccbytesio)
  File "/usr/lib64/python3.9/site-packages/PIL/ImageCms.py", line 164, in __init__
    self._set(core.profile_frombytes(profile.read()))
OSError: cannot open profile from string
```

The PDF looks weird, in the sense that I can see it perfectly fine on my screen, but when I try to select anything, it becomse all garbled. Since it contains some sensitive information, I will provide the PDF encrypted and some limited screenshots.

**To Reproduce**

```bash
ocrmypdf -v1 2016-01.pdf 2016-01-out.pdf
ocrmypdf -v1 --force-ocr 2016-01.pdf 2016-01-out.pdf
```

The PDF (encrypted and armored):

[2016-01.pdf.gpg.txt](https://github.com/jbarlow83/OCRmyPDF/files/5752218/2016-01.pdf.gpg.txt)

**Expected behavior**

Either a message that no text was found, or an attempt to "flatten" the PDF and OCR-scan.

**Screenshots**

Normal looking:

![image](https://user-images.githubusercontent.com/3170771/103314655-f6365a00-4a23-11eb-80b4-0e601bea9da3.png)

Selected the text:

![image](https://user-images.githubusercontent.com/3170771/103314668-fe8e9500-4a23-11eb-9f1e-939cacf72bac.png)

**System**

(reproduced on different systems)

Current one:
 - OS: linux, Fedora 33
 - OCRmyPDF Version: 11.3.3
 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image?
     - `yum -y install ocrmypdf`

**Comment by jbarlow83** [comment]
Thanks for including a test file. 

I found that the document has an ICC profile (which defines its colors), but the profile is corrupt somehow. The profile appears to be a sRGB-type profile, so there shouldn't be an issue with removing it and replacing it with something generic, although the colors might be changed slightly.

You can repair it with pikepdf:
```python
with pikepdf.open('issue706.pdf') as p:
    p.pages[0].images['/Im2'].ColorSpace = pikepdf.Name.DeviceRGB
    p.save('newfile.pdf')
```

**Comment by jbarlow83** [comment]
I'll improve the error message (on the pikepdf side), but I think the best course of action in this situation is to alert the user and abort, because then they can correct it and visually confirm results are acceptable. Software can't make that judgment call.
