### ISSUE TITLE
ERROR - [Errno 13] Permission denied

### ISSUE THREAD

**Issue by seisdr** [jbarlow83/OCRmyPDF#720]
![Screenshot_2021-01-21-20-09-55](https://user-images.githubusercontent.com/45742462/105385666-a747a300-5c24-11eb-91d1-66b15015a82d.png)
trying to do as this guide : https://unix.stackexchange.com/a/377363

**Comment by seisdr** [comment]
```
root@localhost:~# ocrmypdf  k.pdf  scan.pdf
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_sync.py", line 364, in run_pipeline
    check_pages=options.pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_pipeline.py", line 160, in get_pdfinfo
    check_pages=check_pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 840, in __init__
    detailed_analysis=detailed_analysis,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 631, in _pdf_pageinfo_concurrent
    task_finished=update_pageinfo,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_concurrent.py", line 93, in exec_progress_pool
    log_queue: multiprocessing.Queue = multiprocessing.Queue(-1)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
root@localhost:~#
```

**Comment by seisdr** [comment]
```
root@localhost:~# ocrmypdf -v 2    k.pdf  scan.pdf
  DEBUG ocrmypdf - ocrmypdf 11.5.0
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = List of available languages (2):
eng
osd

  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 4.0.0-beta.1
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 9.26
  DEBUG ocrmypdf.helpers - pikepdf mmap disabled
  DEBUG ocrmypdf.helpers - os.symlink(k.pdf, /tmp/ocrmypdf.io.sxgllewv/origin)
  DEBUG ocrmypdf.helpers - os.symlink(/tmp/ocrmypdf.io.sxgllewv/origin, /tmp/ocrmypdf.io.sxgllewv/origin.pdf)
  ERROR ocrmypdf._sync - An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_sync.py", line 364, in run_pipeline
    check_pages=options.pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_pipeline.py", line 160, in get_pdfinfo
    check_pages=check_pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 840, in __init__
    detailed_analysis=detailed_analysis,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 631, in _pdf_pageinfo_concurrent
    task_finished=update_pageinfo,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_concurrent.py", line 93, in exec_progress_pool
    log_queue: multiprocessing.Queue = multiprocessing.Queue(-1)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py",
```

**Comment by jbarlow83** [comment]
This does not look like an ordinary Linux system. Is this Android?

Please don't ignore issue templates, but fill them. I ask those questions because they are what I need to know to help you.

You could try `ocrmypdf --use-threads`

**Comment by seisdr** [comment]
yes it's terminal emulator on android 
and ubuntu 18.04 distro inside

**Comment by seisdr** [comment]
and fake root privileges my device is not rooted

**Comment by seisdr** [comment]
```
root@localhost:~# ocrmypdf --use-threads k.pdf  out.pdf
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_sync.py", line 364, in run_pipeline
    check_pages=options.pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_pipeline.py", line 160, in get_pdfinfo
    check_pages=check_pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 840, in __init__
    detailed_analysis=detailed_analysis,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 631, in _pdf_pageinfo_concurrent
    task_finished=update_pageinfo,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_concurrent.py", line 93, in exec_progress_pool
    log_queue: multiprocessing.Queue = multiprocessing.Queue(-1)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
root@localhost:~#
```

**Comment by seisdr** [comment]
now if I remove /proc from the system files I get
```
spiral@localhost:~$ ocrmypdf  k.pdf  out.pdf
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_sync.py", line 364, in run_pipeline
    check_pages=options.pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_pipeline.py", line 160, in get_pdfinfo
    check_pages=check_pages,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 840, in __init__
    detailed_analysis=detailed_analysis,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/pdfinfo/info.py", line 631, in _pdf_pageinfo_concurrent
    task_finished=update_pageinfo,
  File "/usr/local/lib/python3.6/dist-packages/ocrmypdf/_concurrent.py", line 93, in exec_progress_pool
    log_queue: multiprocessing.Queue = multiprocessing.Queue(-1)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 38] Function not implemented
```

**Comment by seisdr** [comment]
can you add an option to disable whatever requires root to work

**Comment by seisdr** [comment]
I need to translate a pdf 
university is hard man 😂
