### ISSUE TITLE
Scanned jpeg ExifOrientationError: Invalid rotation (0)

### ISSUE THREAD

**Issue by albsch** [jbarlow83/OCRmyPDF#744]
**Describe the bug**
Jpegs produced with `Open Note Scanner` cannot be processed with OCRmyPDF and the process returns `ExifOrientationError: Invalid rotation (0)` as the error message.

**To Reproduce**

```bash
docker run --rm -i --workdir /data -v "$PWD:/data"  jbarlow83/ocrmypdf DOC-20210303-205812.jpg test.pdf --image-dpi _300_
```

Log:

```
docker run --rm -i --workdir /data -v "$PWD:/data"  jbarlow83/ocrmypdf DOC-20210303-205812.jpg test.pdf -v1 --image-dpi 300
ocrmypdf 11.7.0.post5+g25c8c465.d20210303
Running: ['tesseract', '--list-langs']
stdout/stderr = List of available languages (7):
chi_sim
deu
eng
fra
osd
por
spa

Running: ['tesseract', '--version']
Found tesseract 4.1.1
Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
Running: ['gs', '--version']
Found gs 9.50
pikepdf mmap disabled
os.symlink(DOC-20210303-205812.jpg, /tmp/ocrmypdf.io.fbn4mau8/origin)
Input file is not a PDF, checking if it is an image...
Input file is an image
Image seems valid. Try converting to PDF...
imgformat = JPEG
input dpi = 72 x 72
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 354, in run_pipeline
    origin_pdf = triage(
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_pipeline.py", line 143, in triage
    triage_image_file(input_file, output_file, options)
  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_pipeline.py", line 99, in triage_image_file
    img2pdf.convert(
  File "/usr/local/lib/python3.8/dist-packages/img2pdf.py", line 2032, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/usr/local/lib/python3.8/dist-packages/img2pdf.py", line 1374, in read_images
    color, ndpi, imgwidthpx, imgheightpx, rotation, iccp = get_imgmetadata(
  File "/usr/local/lib/python3.8/dist-packages/img2pdf.py", line 1224, in get_imgmetadata
    raise ExifOrientationError("Invalid rotation (%d)" % value)
img2pdf.ExifOrientationError: Invalid rotation (0)
```

**Example file**

[scan.zip](https://github.com/jbarlow83/OCRmyPDF/files/6082263/scan.zip)

**Expected behavior**
No error should happen.

**System**
 - OS: Archlinux, Docker
 - OCRmyPDF Version: 11.7.0.post5+g25c8c465.d20210303

**Comment by albsch** [comment]
It may be an issue with the `img2pdf` library. The library can't process the image file and returns with an error:
```
img2pdf DOC-20210303-205812.jpg  -o out.pdf -v
DEBUG:PIL.TiffImagePlugin:tag: ImageWidth (256) - type: long (4) - value: b'\x00\x00\x0b\xb8'
DEBUG:PIL.TiffImagePlugin:tag: ImageLength (257) - type: long (4) - value: b'\x00\x00\x0f\xa0'
DEBUG:PIL.TiffImagePlugin:tag: Software (305) - type: string (2) Tag Location: 46 - Data Location: 86 - value: <table: 52 bytes>
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x00\x9e'
DEBUG:PIL.TiffImagePlugin:tag: Orientation (274) - type: short (3) - value: b'\x00\x00'
DEBUG:PIL.TiffImagePlugin:tag: DateTime (306) - type: string (2) Tag Location: 82 - Data Location: 138 - value: b'2021:03:03 20:58:12\x00'
DEBUG:PIL.TiffImagePlugin:tag: DateTImeDigitized (36868) - type: string (2) Tag Location: 172 - Data Location: 200 - value: b'2021:03:03 20:58:12\x00'
DEBUG:PIL.TiffImagePlugin:tag: UserComment (37510) - type: string (2) Tag Location: 184 - Data Location: 220 - value: <table: 34 bytes>
DEBUG:PIL.TiffImagePlugin:tag: LightSource (37384) - type: long (4) - value: b'\x00\x00\x00\x00'
DEBUG:root:imgformat = JPEG
DEBUG:root:input dpi = 72 x 72
ERROR:root:error: Invalid rotation (0)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/img2pdf.py", line 3629, in main
    convert(
  File "/usr/lib/python3.9/site-packages/img2pdf.py", line 2032, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/usr/lib/python3.9/site-packages/img2pdf.py", line 1374, in read_images
    color, ndpi, imgwidthpx, imgheightpx, rotation, iccp = get_imgmetadata(
  File "/usr/lib/python3.9/site-packages/img2pdf.py", line 1224, in get_imgmetadata
    raise ExifOrientationError("Invalid rotation (%d)" % value)
img2pdf.ExifOrientationError: Invalid rotation (0)
```

**Comment by jbarlow83** [comment]
Please report this as an img2pdf issue.

**Comment by albsch** [comment]
Ok, I openend an issue [here](https://gitlab.mister-muffin.de/josch/img2pdf/issues/90)

**Comment by albsch** [comment]
This might be an issue with the app after all:
https://github.com/allgood/OpenNoteScanner/issues/248
I'm closing this for now.
