### ISSUE TITLE
This error normally occurs when ocrmypdf can't find the Leptonica

### ISSUE THREAD

**Issue by mrkgoh** [jbarlow83/OCRmyPDF#757]
**Trying to install via pip install for my python script**
The error I got along the way: This error normally occurs when ocrmypdf can't find the Leptonica

**To Reproduce**
First I do:
```
id@nasname:~$ git clone -b master https://github.com/jbarlow83/OCRmyPDF.git
Cloning into 'OCRmyPDF'...
remote: Enumerating objects: 426, done.
remote: Counting objects: 100% (426/426), done.
remote: Compressing objects: 100% (217/217), done.
remote: Total 17759 (delta 216), reused 338 (delta 178), pack-reused 17333
Receiving objects: 100% (17759/17759), 62.36 MiB | 13.39 MiB/s, done.
Resolving deltas: 100% (11630/11630), done.
```

then:
```
id@nasname:~$ source venv/bin/activate
(venv) id@nasname:~$ cd OCRmyPDF
(venv) id@nasname:~/OCRmyPDF$ pip install .
Processing /volume1/homes/admin/OCRmyPDF
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pluggy<1.0,>=0.13.0 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (0.13.1)
Requirement already satisfied: setuptools in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (52.0.0)
Requirement already satisfied: pdfminer.six!=20200720,<=20201018,>=20191110 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (20200517)
Requirement already satisfied: cffi>=1.9.1 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (1.14.5)
Requirement already satisfied: tqdm>=4 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (4.60.0)
Requirement already satisfied: Pillow>=8.1.2 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (8.2.0)
Requirement already satisfied: img2pdf<0.5,>=0.3.0 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (0.4.0)
Requirement already satisfied: coloredlogs>=14.0 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (15.0)
Requirement already satisfied: reportlab>=3.5.66 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (3.5.66)
Requirement already satisfied: pikepdf>=2.10.0 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from ocrmypdf==11.7.3.post54+g9416e850) (2.10.0)
Requirement already satisfied: pycparser in /volume1/homes/admin/venv/lib/python3.8/site-packages (from cffi>=1.9.1->ocrmypdf==11.7.3.post54+g9416e850) (2.20)
Requirement already satisfied: humanfriendly>=9.1 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from coloredlogs>=14.0->ocrmypdf==11.7.3.post54+g9416e850) (9.1)
Requirement already satisfied: pycryptodome in /volume1/homes/admin/venv/lib/python3.8/site-packages (from pdfminer.six!=20200720,<=20201018,>=20191110->ocrmypdf==11.7.3.post54+g9416e850) (3.10.1)
Requirement already satisfied: sortedcontainers in /volume1/homes/admin/venv/lib/python3.8/site-packages (from pdfminer.six!=20200720,<=20201018,>=20191110->ocrmypdf==11.7.3.post54+g9416e850) (2.3.0)
Requirement already satisfied: chardet in /volume1/homes/admin/venv/lib/python3.8/site-packages (from pdfminer.six!=20200720,<=20201018,>=20191110->ocrmypdf==11.7.3.post54+g9416e850) (4.0.0)
Requirement already satisfied: lxml>=4.0 in /volume1/homes/admin/venv/lib/python3.8/site-packages (from pikepdf>=2.10.0->ocrmypdf==11.7.3.post54+g9416e850) (4.6.2)
Building wheels for collected packages: ocrmypdf
  Building wheel for ocrmypdf (PEP 517) ... done
  Created wheel for ocrmypdf: filename=ocrmypdf-11.7.3.post54+g9416e850-py36-none-any.whl size=137219 sha256=99a681ab384032f8a8e285d735a12f0b1067fe9ea211441a1b2b9a0aa4f55ac4
  Stored in directory: /tmp/pip-ephem-wheel-cache-9j6mcuiy/wheels/1c/87/50/56b2c20bc856120787aec411ee6d9152422cbc3ad38baad31d
Successfully built ocrmypdf
Installing collected packages: ocrmypdf
Successfully installed ocrmypdf-11.7.3.post54+g9416e850
```

when I do this here is my error:
```
(venv) id@nasname:~/OCRmyPDF$ ocrmypdf --version
Traceback (most recent call last):
  File "/volume1/homes/admin/venv/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/volume1/homes/admin/venv/lib/python3.8/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/volume1/homes/admin/venv/lib/python3.8/site-packages/ocrmypdf/leptonica.py", line 44, in <module>
    raise MissingDependencyError(
ocrmypdf.exceptions.MissingDependencyError:
        ---------------------------------------------------------------------
        This error normally occurs when ocrmypdf can't find the Leptonica
        library, which is usually installed with Tesseract OCR. It could be that
        Tesseract is not installed properly, we can't find the installation
        on your system PATH environment variable.

        The library we are looking for is usually called:
            liblept-5.dll   (Windows)
            liblept*.dylib  (macOS)
            liblept*.so     (Linux/BSD)

        Please review our installation procedures to find a solution:
            https://ocrmypdf.readthedocs.io/en/latest/installation.html
        ---------------------------------------------------------------------`
```
**System (please complete the following information):**
 - OS: Synology DSM 220+ DSM 6.2.4-25556
 - Python version: Python 3.8.6 (default, Jan  4 2021, 16:11:49)
 - OCRmyPDF version: ocrmypdf-11.7.3.post54+g9416e850

**Comment by jbarlow83** [comment]
As the error suggestions, you need to build and install Leptonica, Tesseract and some other software to do a native install.
Most Linux users have a package manager that provides all of that makes it relatively easy. Synology does not.

I don't recommend trying to do all of this on a Synology. Docker is the easier solution. Because I don't recommend trying to do this I will close the issue.
