### ISSUE TITLE
ocrmypdf.exceptions.TesseractConfigError: Error occurred while parsing a Tesseract configuration file """

### ISSUE THREAD

**Issue by AmirthaKrishnan** [jbarlow83/OCRmyPDF#763]
import ocrmypdf

if __name__ == '__main__':  # To ensure correct behavior on Windows and macOS
    ocrmypdf.ocr('input.pdf', 'output.pdf', deskew=True)
also installed Tesseract 5.0
ghostScript 

why am getting this error

Scanning contents: 100%|██████████| 2/2 [00:00<00:00, 127.93page/s]
OCR:   0%|          | 0.0/2.0 [00:00<?, ?page/s][tesseract] Warning: Parameter not found: enable_new_segsearch
OCR:   0%|          | 0.0/2.0 [00:03<?, ?page/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Tools\Py3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\_sync.py", line 214, in exec_page_sync
    (ocr_out, text_out) = ocr_engine_textonly_pdf(ocr_image_out, page_context)
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\_pipeline.py", line 640, in ocr_engine_textonly_pdf
    ocr_engine.generate_pdf(
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py", line 169, in generate_pdf
    tesseract.generate_pdf(
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\_exec\tesseract.py", line 340, in generate_pdf
    tesseract_log_output(stdout)
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\_exec\tesseract.py", line 196, in tesseract_log_output
    raise TesseractConfigError(problem)
ocrmypdf.exceptions.TesseractConfigError: Error occurred while parsing a Tesseract configuration file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Dev/ocrMyPdf/ocr/ocrMyPdf.py", line 4, in <module>
    ocrmypdf.ocr('input.pdf', 'output.pdf')
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\api.py", line 326, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\_sync.py", line 373, in run_pipeline
    exec_concurrent(context)
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\_sync.py", line 272, in exec_concurrent
    exec_progress_pool(
  File "D:\ocrMyPdf\lib\site-packages\ocrmypdf\_concurrent.py", line 112, in exec_progress_pool
    for result in results:
  File "D:\Tools\Py3\lib\multiprocessing\pool.py", line 868, in next
    raise value
ocrmypdf.exceptions.TesseractConfigError: Error occurred while parsing a Tesseract configuration file

Process finished with exit code 1

**Comment by jbarlow83** [comment]
I believe this means Tesseract is not installed or configured properly, or perhaps there is a mixture of files from different versions of Tesseract.

Please try running some example Tesseract commands and make sure that Tesseract is working properly from the command line.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by githubkusi** [comment]
I get the very same error

**Comment by jbarlow83** [comment]
Anaconda seems to cause this currently.

**Comment by githubkusi** [comment]
The tesseract command actually completes w/o error. Calling

    tesseract -l eng -c textonly_pdf=1 /tmp/ocrmypdf.io.qdrq2wu0/000001_ocr.png /tmp/ocrmypdf.io.qdrq2wu0/000001_ocr_tess pdf txt 

(either command line or in tesseract.py, command ```p = run(args_tesseract....)```)

results in a file 000001_ocr_tess.txt with valid content.

**Comment by jbarlow83** [comment]
That preamble about `tesseract_opencl_profile_devices` suggests you have a custom build of Tesseract on your PATH. The opencl extension isn't exactly stable or well maintained and I doubt anyone is shipping it in a distribution. You may also have a usr/share/tesseract/tessdata that doesn't match this compiled version of tesseract. If you want support you'll need to open a new issue and explain your whole configuration in detail.
