### ISSUE TITLE
subprocess circular import error

### ISSUE THREAD

**Issue by ajaykumarbharaj** [jbarlow83/OCRmyPDF#775]
**Describe the bug**
use of python keywords "subprocess" as package name for windows registry is causing circular import error 

**To Reproduce**
run __main__.py in debug mode

**Expected behavior**
What did you expected to happen?

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Python version: 3.8.8
 - OCRmyPDF version: 12.0.1

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?

**Additional context**

**Comment by jbarlow83** [comment]
Hi. Can you describe what "running main.py in debug mode" means? What command line did you run, or did you run this in an IDE? Can you also the full stack trace provided by Python?

**Comment by ajaykumarbharaj** [comment]
yes i was running this in pycharm IDE and was debugging it with __main__.py as an entry point

`"C:\Users\xxxxxxx\Anaconda3\envs\ocrmypdf\python.exe" "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 64903 --file "C:/Users/xxxxxxx/Project/OCRmyPDF/src/ocrmypdf/__main__.py" --output-type pdf --force-ocr "C:\Users\xxxxxxx\Project\OCRmyPDF\test_data\sample.pdf" "C:\Users\xxxxxxx\Project\OCRmyPDF\test_data\output.pdf"
pydev debugger: process 26656 is connecting
Connected to pydev debugger (build 202.7660.27)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xxxxxxx\Project\OCRmyPDF\src\ocrmypdf\__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "C:\Users\xxxxxxx\Project\OCRmyPDF\src\ocrmypdf\helpers.py", line 22, in <module>
    import pikepdf
  File "C:\Users\xxxxxxx\Anaconda3\envs\ocrmypdf\lib\site-packages\pikepdf\__init__.py", line 50, in <module>
    from .models import (
  File "C:\Users\xxxxxxx\Anaconda3\envs\ocrmypdf\lib\site-packages\pikepdf\models\__init__.py", line 12, in <module>
    from .image import PdfImage, PdfInlineImage, UnsupportedImageTypeError
  File "C:\Users\xxxxxxx\Anaconda3\envs\ocrmypdf\lib\site-packages\pikepdf\models\image.py", line 20, in <module>
    from pikepdf import (
  File "C:\Users\xxxxxxx\Anaconda3\envs\ocrmypdf\lib\site-packages\pikepdf\jbig2.py", line 8, in <module>
    from subprocess import DEVNULL, PIPE, CalledProcessError, run
  File "C:\Users\xxxxxxx\Box Sync\Project\OCRmyPDF\src\ocrmypdf\subprocess\__init__.py", line 19, in <module>
    from subprocess import PIPE, STDOUT, CalledProcessError, CompletedProcess, Popen
ImportError: cannot import name 'PIPE' from partially initialized module 'subprocess' (most likely due to a circular import) (C:\Users\xxxxxxx\Project\OCRmyPDF\src\ocrmypdf\subprocess\__init__.py)
python-BaseException`

**Comment by jbarlow83** [comment]
I think you should install ocrmypdf as a [module in development mode](https://stackoverflow.com/questions/26556865/anaconda-equivalent-of-setup-py-develop), and configure your IDE to execute the `ocrmypdf` module in the current virtual environment, rather than the file `__main__.py`. 

I am not very familiar with Anaconda or PyCharm.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
