### ISSUE TITLE
PCRmyPDF crashes when PDF contains non-text pages

### ISSUE THREAD

**Issue by tomasmueller** [jbarlow83/OCRmyPDF#796]
**Describe the bug**
When i try to ocr a pdf that contain pages only with pictures ocrmypdf crashes.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.8.5
 - OCRmyPDF version: 12.2.0

**Installation**
Installed with pip

**Additional context**
I have a script that creates a pdf from jpg-images with
`gm convert input output.pdf`
and then ocr that file with
`ocrmypdf -l deu+eng --output-type pdf input.pdf output.pdf`

creating the pdf works ocrmypdf crashes when the pdf contains images without text. I have this behaviour only with one of my projects, never before. When i create the pdf without the non-text pages ocrmypdf works. Thats the error i have:

```
An exception occurred while executing the pipeline
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 189, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 115, in make_intermediate_images
    rasterize_out = rasterize(
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 453, in rasterize
    page_context.plugin_manager.hook.rasterize_pdf_page(
  File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page
    ghostscript.rasterize_pdf(
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/_exec/ghostscript.py", line 124, in rasterize_pdf
    with Image.open(BytesIO(p.stdout)) as im:
  File "/home/ich/.local/lib/python3.8/site-packages/PIL/Image.py", line 3009, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/home/ich/.local/lib/python3.8/site-packages/PIL/Image.py", line 2996, in _open_core
    _decompression_bomb_check(im.size)
  File "/home/ich/.local/lib/python3.8/site-packages/PIL/Image.py", line 2905, in _decompression_bomb_check
    raise DecompressionBombError(
PIL.Image.DecompressionBombError: Image size (896250000 pixels) exceeds limit of 256000000 pixels, could be decompression bomb DOS attack.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 374, in run_pipeline
    exec_concurrent(context, executor)
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 271, in exec_concurrent
    executor(
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/home/ich/.local/lib/python3.8/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 132, in _execute
    for result in results:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
PIL.Image.DecompressionBombError: Image size (896250000 pixels) exceeds limit of 256000000 pixels, could be decompression bomb DOS attack
```

**Comment by jbarlow83** [comment]
Use `--max-image-mpixels 1000` to try raiding the size of image, assuming that you are expecting some of your pages to have >900 megapixels. This does happen for very large pages like A0 sized CAD plots at high resolution.

If not, it may be that your script is creating images with excessively high resolution.

**Comment by tomasmueller** [comment]
yes there are some images with a very high resolution. i fixed the script so that all images have the same. when the resolution of the images are higher then 900mpx i will have the problem again?

whats when i use --max-image-mpixels 1000 for all files as default? is the process slowing down?

**Comment by jbarlow83** [comment]
In the vast majority of cases, images larger than 256M pixels are not expected and are possible decompression bombs. PIL.Image.DecompressionBombError is a sanity check. When you use --max-image-mpixels, you are telling ocrmypdf to adjust the threshold higher than default. It will be slower but the main concern is denial of service or malicious files that that use decompression bombs. 

At a certain other ocrmypdf dependencies will also refuse to work on extremely large images. I believe Tesseract will refuse any image large than 4 GB uncompressed, regardless of its dimensions.

**Comment by jbarlow83** [comment]
Closing since this is "works as designed" behavior.
