### ISSUE TITLE
[api] Allow for passing io.BytesIO or pikepdf.Pdf as input_file

### ISSUE THREAD

**Issue by mara004** [jbarlow83/OCRmyPDF#798]
I tried to pass an io.BytesIO PDF to `ocrmypdf.ocr()` as `input_file`, which ended up with the following error:
```
cannot identify image file '<_io.BytesIO object at 0x7f3c979c62c0>'
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 50, in triage_image_file
    im = Image.open(input_file)
  File "/home/me/.local/lib/python3.8/site-packages/PIL/Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/tmp/ocrmypdf.io.walueh0i/stream'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "package_book.py", line 75, in <module>
    nodegraph.run()
  File "/home/me/projects/pdfnodegraph/pdfnodegraph/processing/nodegraph.py", line 327, in run
    node.compile_output()
  File "/home/me/projects/pdfnodegraph/pdfnodegraph/processing/nodes.py", line 83, in compile_output
    self.output = [self.arranging_method(*input_object, **self.settings)]
  File "/home/me/projects/pdfnodegraph/pdfnodegraph/processing/export/exporting.py", line 179, in exporter
    dest_doc, outbytes = ocr.add_text_layer(dest_doc, svargs, ocr_options)
  File "/home/me/projects/pdfnodegraph/pdfnodegraph/processing/export/ocr.py", line 39, in add_text_layer
    ocrmypdf.ocr(
  File "/home/me/.local/lib/python3.8/site-packages/ocrmypdf/api.py", line 340, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/home/me/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 354, in run_pipeline
    origin_pdf = triage(
  File "/home/me/.local/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 143, in triage
    triage_image_file(input_file, output_file, options)
  File "/home/me/.local/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 54, in triage_image_file
    raise UnsupportedImageFormatError() from e
ocrmypdf.exceptions.UnsupportedImageFormatError
```
It would be nice if ocrmypdf could directly accept `io.BytesIO` (or `pikepdf.Pdf`) objects to avoid tempfiles.

**Comment by jbarlow83** [comment]
The following works for me:

```python
import io, ocrmypdf
bio = io.BytesIO(open('tests/resources/jbig2.pdf', 'rb').read())
ocrmypdf.ocr(bio, '/dev/null',force_ocr=True)
```

However, if another process calls `bio.read()` it will set the stream to the end of the file, and that will trigger the same exception. Likewise, if you write to a `BytesIO`, the cursor will be at the end of the file. Use `BytesIO.seek(0)` to reset the stream to the beginning and it should work.

Accepting `pikepdf.Pdf` is a reasonable idea.

**Comment by mara004** [comment]
> Use BytesIO.seek(0) to reset the stream to the beginning and it should work.

Oh yes, I'm silly. I should have known that, sorry.
