### ISSUE TITLE
tqdm error causing ocrmypdf to crash whilst performing ocr

### ISSUE THREAD

**Issue by mara004** [jbarlow83/OCRmyPDF#870]
**Describe the bug**
After updating packages and running my local test suite, I noticed that OCR suddenly terminates due to an error in or related to the tqdm library. The issue is constantly reproducible for me.
```
Scanning contents: 8page [00:00, 371.80page/s]                                                                                                              
OCR:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▎             | 3.5/4.0 [00:03<00:01,  3.30s/page][tesseract] lots of diacritics - possibly poor OCR
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 136, in _execute
    task_finished(result, pbar)
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 263, in update_page
    pbar.update()
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 1104, in update
    self.display()
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 1293, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 962, in __repr__
    return self.format_meter(**self.format_dict)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 322, in format_meter
    total *= unit_scale
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 149, in _execute
    executor.shutdown(wait=False, cancel_futures=True)
TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[...]
    ocrmypdf.ocr(
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "~/.local/lib/python3.8/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 153, in _execute
    log_queue.put_nowait(None)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 940, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 1166, in close
    self.display(pos=pos)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 1293, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 962, in __repr__
    return self.format_meter(**self.format_dict)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 322, in format_meter
    total *= unit_scale
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'

```

**To Reproduce**
I am invoking `ocrmypdf.ocr()` from Python code:
```python3
    ocrmypdf.ocr(
        input_file = inbytes,
        output_file = outbytes,
        lang = 'deu',
    )
```

**Expected behavior**
OCRmyPDF should finish OCR properly and not crash

**System (please complete the following information):**
 - OS: KDE Neon Linux (based on Ubuntu 20.04)
 - Python version: 3.8.10
 - OCRmyPDF version: 13.1.1 (latest)
 - tqdm version: 4.30.0

**Installation**
OCRmyPDF was installed using `pip`.

**Comment by mara004** [comment]
Updating tqdm to the latest version `4.62.3` seems to fix the issue.

**Comment by jbarlow83** [comment]
Probably
